using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace medipro.api.Medipro.Models.NewModels.EyeDocs
{
    public class OcularExaminationAll_dt
    {
        public string mrdno { get; set; }
        public DateTime ddate { get; set; }
        public int hospid { get; set; }
        public bool proptosis_od_tick { get; set; }
        public bool proptosis_os_tick { get; set; }
        public bool eom_od_tick { get; set; }
        public string eom_od { get; set; }
        public bool eom_os_tick { get; set; }
        public string eom_os { get; set; }
        public bool lid_od_tick { get; set; }
        public bool lid_dermato_od_tick { get; set; }
        public bool lid_xanthelasma_od_tick { get; set; }
        public bool lid_pbt_od_tick { get; set; }
        public bool lid_ptosis_od_tick { get; set; }
        public bool lid_entropion_od_tick { get; set; }
        public bool lid_ectropion_od_tick { get; set; }
        public bool lid_chalazion_od_tick { get; set; }
        public bool lid_stye_od_tick { get; set; }
        public bool lid_abscess_od_tick { get; set; }
        public bool lid_laceration_od_tick { get; set; }
        public bool lid_others_od_tick { get; set; }
        public string lid_others_od { get; set; }
        public bool lid_os_tick { get; set; }
        public bool lid_dermato_os_tick { get; set; }
        public bool lid_xanthelasma_os_tick { get; set; }
        public bool lid_pbt_os_tick { get; set; }
        public bool lid_ptosis_os_tick { get; set; }
        public bool lid_entropion_os_tick { get; set; }
        public bool lid_ectropion_os_tick { get; set; }
        public bool lid_chalazion_os_tick { get; set; }
        public bool lid_stye_os_tick { get; set; }
        public bool lid_abscess_os_tick { get; set; }
        public bool lid_laceration_os_tick { get; set; }
        public bool lid_others_os_tick { get; set; }
        public string lid_others_os { get; set; }
        public bool conjunct_od_tick { get; set; }
        public bool conjunct_congestion_od_tick { get; set; }
        public bool conjunct_nevus_od_tick { get; set; }
        public bool conjunct_bleb_od_tick { get; set; }
        public bool conjunct_laceration_od_tick { get; set; }
        public bool conjunct_deposteroid_od_tick { get; set; }
        public bool conjunct_ptery_od_tick { get; set; }
        public bool conjunct_ping_od_tick { get; set; }
        public bool conjunct_others_od_tick { get; set; }
        public string conjunct_others_od { get; set; }
        public bool conjunct_os_tick { get; set; }
        public bool conjunct_congestion_os_tick { get; set; }
        public bool conjunct_nevus_os_tick { get; set; }
        public bool conjunct_bleb_os_tick { get; set; }
        public bool conjunct_laceration_os_tick { get; set; }
        public bool conjunct_deposteroid_os_tick { get; set; }
        public bool conjunct_ptery_os_tick { get; set; }
        public bool conjunct_ping_os_tick { get; set; }
        public bool conjunct_others_os_tick { get; set; }
        public string conjunct_others_os { get; set; }
        public bool sclera_od_tick { get; set; }
        public bool sclera_staphy_od_tick { get; set; }
        public bool sclera_ict_od_tick { get; set; }
        public bool sclera_thinning_od_tick { get; set; }
        public bool sclera_melting_od_tick { get; set; }
        public bool sclera_lacerat_od_tick { get; set; }
        public bool sclera_others_od_tick { get; set; }
        public string sclera_others_od { get; set; }
        public bool sclera_os_tick { get; set; }
        public bool sclera_staphy_os_tick { get; set; }
        public bool sclera_ict_os_tick { get; set; }
        public bool sclera_thinning_os_tick { get; set; }
        public bool sclera_melting_os_tick { get; set; }
        public bool sclera_lacerat_os_tick { get; set; }
        public bool sclera_others_os_tick { get; set; }
        public string sclera_others_os { get; set; }
        public bool cornea_od_tick { get; set; }
        public bool cornea_staphy_od_tick { get; set; }
        public bool cornea_ict_od_tick { get; set; }
        public bool cornea_thinning_od_tick { get; set; }
        public bool cornea_melting_od_tick { get; set; }
        public bool cornea_lacerat_od_tick { get; set; }
        public bool cornea_others_od_tick { get; set; }
        public string cornea_others_od { get; set; }
        public bool cornea_os_tick { get; set; }
        public bool cornea_staphy_os_tick { get; set; }
        public bool cornea_ict_os_tick { get; set; }
        public bool cornea_thinning_os_tick { get; set; }
        public bool cornea_melting_os_tick { get; set; }
        public bool cornea_lacerat_os_tick { get; set; }
        public bool cornea_others_os_tick { get; set; }
        public string cornea_others_os { get; set; }
        public bool anterchamb_od_tick { get; set; }
        public bool anterchamb_mh_od_tick { get; set; }
        public bool anterchamb_pc_od_tick { get; set; }
        public bool anterchamb_nf_od_tick { get; set; }
        public bool anterchamb_others_od_tick { get; set; }
        public string anterchamb_others_od { get; set; }
        public bool anterchamb_os_tick { get; set; }
        public bool anterchamb_mh_os_tick { get; set; }
        public bool anterchamb_pc_os_tick { get; set; }
        public bool anterchamb_nf_os_tick { get; set; }
        public bool anterchamb_others_os_tick { get; set; }
        public string anterchamb_others_os { get; set; }
        public bool iris_od_tick { get; set; }
        public bool iris_hetero_od_tick { get; set; }
        public bool iris_atrophy_od_tick { get; set; }
        public bool iris_nevus_od_tick { get; set; }
        public bool iris_sid_od_tick { get; set; }
        public bool iris_anirid_od_tick { get; set; }
        public bool iris_others_od_tick { get; set; }
        public string iris_others_od { get; set; }
        public bool iris_os_tick { get; set; }
        public bool iris_hetero_os_tick { get; set; }
        public bool iris_atrophy_os_tick { get; set; }
        public bool iris_nevus_os_tick { get; set; }
        public bool iris_sid_os_tick { get; set; }
        public bool iris_anirid_os_tick { get; set; }
        public bool iris_others_os_tick { get; set; }
        public string iris_others_os { get; set; }
        public bool pupil_od_tick { get; set; }
        public bool pupil_corecto_od_tick { get; set; }
        public bool pupil_polyco_od_tick { get; set; }
        public bool pupil_ppm_od_tick { get; set; }
        public bool pupil_ppi_od_tick { get; set; }
        public bool pupil_dsp_od_tick { get; set; }
        public bool pupil_others_od_tick { get; set; }
        public string pupil_others_od { get; set; }
        public bool pupil_os_tick { get; set; }
        public bool pupil_corecto_os_tick { get; set; }
        public bool pupil_polyco_os_tick { get; set; }
        public bool pupil_ppm_os_tick { get; set; }
        public bool pupil_ppi_os_tick { get; set; }
        public bool pupil_dsp_os_tick { get; set; }
        public bool pupil_others_os_tick { get; set; }
        public string pupil_others_os { get; set; }
        public bool pupil_rti_od_tick { get; set; }
        public bool pupil_rti_rapd_od_tick { get; set; }
        public bool pupil_rti_slugreact_od_tick { get; set; }
        public bool pupil_rti_hippus_od_tick { get; set; }
        public bool pupil_rti_aap_od_tick { get; set; }
        public bool pupil_rti_apd_od_tick { get; set; }
        public bool pupil_rti_others­_od_tick { get; set; }
        public string pupil_rti_others_od { get; set; }
        public bool pupil_rti_os_tick { get; set; }
        public bool pupil_rti_rapd_os_tick { get; set; }
        public bool pupil_rti_slugreact_os_tick { get; set; }
        public bool pupil_rti_hippus_os_tick { get; set; }
        public bool pupil_rti_aap_os_tick { get; set; }
        public bool pupil_rti_apd_os_tick { get; set; }
        public bool pupil_rti_others­_os_tick { get; set; }
        public string pupil_rti_others_os { get; set; }
        public bool lens_phakic_od_tick { get; set; }
        public bool lens_pseuphakic_od_tick { get; set; }
        public bool lens_aphakic_od_tick { get; set; }
        public bool lens_phakic_os_tick { get; set; }
        public bool lens_pseuphakic_os_tick { get; set; }
        public bool lens_aphakic_os_tick { get; set; }
        public bool caps_od_tick { get; set; }
        public bool caps_pseudo_od_tick { get; set; }
        public bool caps_pco_od_tick { get; set; }
        public bool caps_others_od_tick { get; set; }
        public string caps_others_od { get; set; }
        public bool caps_os_tick { get; set; }
        public bool caps_pseudo_os_tick { get; set; }
        public bool caps_pco_os_tick { get; set; }
        public bool caps_others_os_tick { get; set; }
        public string caps_others_os { get; set; }
        public bool pos_phacod_od_tick { get; set; }
        public bool pos_sublux_od_tick { get; set; }
        public bool pos_disloc_od_tick { get; set; }
        public bool pos_none_od_tick { get; set; }
        public bool pos_phacod_os_tick { get; set; }
        public bool pos_sublux_os_tick { get; set; }
        public bool pos_disloc_os_tick { get; set; }
        public bool pos_none_os_tick { get; set; }
        public bool cataract_tick { get; set; }
        public bool nucopal_n0_od_tick { get; set; }
        public bool nucopal_n1_od_tick { get; set; }
        public bool nucopal_n2_od_tick { get; set; }
        public bool nucopal_n3_od_tick { get; set; }
        public bool nucopal_n4_od_tick { get; set; }
        public bool nucopal_notgrade_od_tick { get; set; }
        public bool nucopal_n0_os_tick { get; set; }
        public bool nucopal_n1_os_tick { get; set; }
        public bool nucopal_n2_os_tick { get; set; }
        public bool nucopal_n3_os_tick { get; set; }
        public bool nucopal_n4_os_tick { get; set; }
        public bool nucopal_notgrade_os_tick { get; set; }
        public bool cortical_c0_od_tick { get; set; }
        public bool cortical_ctr_od_tick { get; set; }
        public bool cortical_c1_od_tick { get; set; }
        public bool cortical_c2_od_tick { get; set; }
        public bool cortical_c3_od_tick { get; set; }
        public bool cortical_c4_od_tick { get; set; }
        public bool cortical_c5_od_tick { get; set; }
        public bool cortical_notgrade_od_tick { get; set; }
        public bool cortical_c0_os_tick { get; set; }
        public bool cortical_ctr_os_tick { get; set; }
        public bool cortical_c1_os_tick { get; set; }
        public bool cortical_c2_os_tick { get; set; }
        public bool cortical_c3_os_tick { get; set; }
        public bool cortical_c4_os_tick { get; set; }
        public bool cortical_c5_os_tick { get; set; }
        public bool cortical_notgrade_os_tick { get; set; }
        public bool psc_p0_od_tick { get; set; }
        public bool psc_p1_od_tick { get; set; }
        public bool psc_p2_od_tick { get; set; }
        public bool psc_p3_od_tick { get; set; }
        public bool psc_p4_od_tick { get; set; }
        public bool psc_notgrade_od_tick { get; set; }
        public bool psc_p0_os_tick { get; set; }
        public bool psc_p1_os_tick { get; set; }
        public bool psc_p2_os_tick { get; set; }
        public bool psc_p3_os_tick { get; set; }
        public bool psc_p4_os_tick { get; set; }
        public bool psc_notgrade_os_tick { get; set; }
        public bool maturecat_od_tick { get; set; }
        public bool maturecat_os_tick { get; set; }
        public bool compact_od_tick { get; set; }
        public bool compact_os_tick { get; set; }
        public bool vitreous_od_tick { get; set; }
        public bool vitreous_pvd_od_tick { get; set; }
        public bool vitreous_vh_od_tick { get; set; }
        public bool vitreous_oparities_od_tick { get; set; }
        public bool vitreous_other_od_tick { get; set; }
        public string vitreous_other_od { get; set; }
        public bool vitreous_os_tick { get; set; }
        public bool vitreous_pvd_os_tick { get; set; }
        public bool vitreous_vh_os_tick { get; set; }
        public bool vitreous_oparities_os_tick { get; set; }
        public bool vitreous_other_os_tick { get; set; }
        public string vitreous_other_os { get; set; }
        public string vitreous_remarks_od { get; set; }
        public string vitreous_remarks_os { get; set; }
        public bool retina_od_tick { get; set; }
        public bool retina_os_tick { get; set; }
        public string retina_od { get; set; }
        public string retina_os { get; set; }
        public bool disc_od_tick { get; set; }
        public bool disc_os_tick { get; set; }
        public string disc_od { get; set; }
        public string disc_os { get; set; }
        public bool cdr_od_tick { get; set; }
        public string cdr_od { get; set; }
        public bool cdr_os_tick { get; set; }
        public string cdr_os { get; set; }
        public bool macula_od_tick { get; set; }
        public bool macula_erm_od_tick { get; set; }
        public bool macula_hole_od_tick { get; set; }
        public bool macula_hemorage_od_tick { get; set; }
        public bool macula_edema_od_tick { get; set; }
        public bool macula_other_od_tick { get; set; }
        public string macula_other_od { get; set; }
        public bool macula_os_tick { get; set; }
        public bool macula_erm_os_tick { get; set; }
        public bool macula_hole_os_tick { get; set; }
        public bool macula_hemorage_os_tick { get; set; }
        public bool macula_edema_os_tick { get; set; }
        public bool macula_other_os_tick { get; set; }
        public string macula_other_os { get; set; }
        public bool vessels_od_tick { get; set; }
        public string vessels_od { get; set; }
        public bool vessels_os_tick { get; set; }
        public string vessels_os { get; set; }
        public bool periphery_od_tick { get; set; }
        public string periphery_od { get; set; }
        public bool periphery_os_tick { get; set; }
        public string periphery_os { get; set; }
        public bool tear_film_od_tick { get; set; }
        public string tear_flim_od { get; set; }
        public bool tear_flim_os_tick { get; set; }
        public string tear_flim_os { get; set; }
        public bool tbvt_od_tick { get; set; }
        public string tbvt_od { get; set; }
        public bool tbvt_os_tick { get; set; }
        public string tbvt_os { get; set; }
    }

    public class OcularExaminationInsert_dt
    {
        public string mrdno { get; set; }
        public DateTime ddate { get; set; }
        public int userid { get; set; }
        public DateTime biltime { get; set; }
        public int hospid { get; set; }
    }

    public class OcularExaminationUpdate_dt
    {
        public string mrdno { get; set; }
        public DateTime ddate { get; set; }
        public int userid { get; set; }
        public DateTime biltime { get; set; }
        public int hospid { get; set; }
    }

    public class OcularExaminationSelect_dt
    {
        public int sn { get; set; }
        public string mrdno { get; set; }
        public DateTime ddate { get; set; }
        public int userid { get; set; }
        public DateTime biltime { get; set; }
        public int hospid { get; set; }
    }

    public class OcularExaminationDelete_dt
    {
        public string mrdno { get; set; }
    }
}