using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace medipro.api.Medipro.Models.NewModels.EyeDocs
{
    public class Past_Eye_HistoryAll_dt
    {
        public string mrdno { get; set; }
        public int hospid { get; set; }
        public DateTime ddate { get; set; }
        public bool eyeproblem_od_tick { get; set; }
        public bool eyeproblem_glaucoma_od_tick { get; set; }
        public string eyeproblem_glaucoma_od { get; set; }
        public bool eyeproblem_cataract_od_tick { get; set; }
        public string eyeproblem_cataract_od { get; set; }
        public bool eyeproblem_retina_od_tick { get; set; }
        public string eyeproblem_retina_od { get; set; }
        public bool eyeproblem_squint_od_tick { get; set; }
        public string eyeproblem_squint_od { get; set; }
        public bool eyeproblem_corneal_od_tick { get; set; }
        public string eyeproblem_corneal_od { get; set; }
        public bool eyeproblem_opalrelated_od_tick { get; set; }
        public string eyeproblem_opalrelated_od { get; set; }
        public bool eyeproblem_uveal_od_tick { get; set; }
        public string eyeproblem_uveal_od { get; set; }
        public bool eyeproblem_neuro_od_tick { get; set; }
        public string eyeproblem_neuro_od { get; set; }
        public bool eyeproblem_others_od_tick { get; set; }
        public string eyeproblem_others_od { get; set; }
        public bool eyeproblem_os_tick { get; set; }
        public bool eyeproblem_glaucoma_os_tick { get; set; }
        public string eyeproblem_glaucoma_os { get; set; }
        public bool eyeproblem_cataract_os_tick { get; set; }
        public string eyeproblem_cataract_os { get; set; }
        public bool eyeproblem_retina_os_tick { get; set; }
        public string eyeproblem_retina_os { get; set; }
        public bool eyeproblem_squint_os_tick { get; set; }
        public string eyeproblem_squint_os { get; set; }
        public bool eyeproblem_corneal_os_tick { get; set; }
        public string eyeproblem_corneal_os { get; set; }
        public bool eyeproblem_opalrelated_os_tick { get; set; }
        public string eyeproblem_opalrelated_os { get; set; }
        public bool eyeproblem_uveal_os_tick { get; set; }
        public string eyeproblem_uveal_os { get; set; }
        public bool eyeproblem_neuro_os_tick { get; set; }
        public string eyeproblem_neuro_os { get; set; }
        public bool eyeproblem_others_os_tick { get; set; }
        public string eyeproblem_others_os { get; set; }
        public string eyeprob_remarks_od { get; set; }
        public string eyeprob_remarks_os { get; set; }
        public bool trauma_od_tick { get; set; }
        public bool trauma_blunt_od_tick { get; set; }
        public string trauma_blunt_od { get; set; }
        public bool trauma_penetrating_od_tick { get; set; }
        public string trauma_penetrating_od { get; set; }
        public bool trauma_others_od_tick { get; set; }
        public string trauma_others_od { get; set; }
        public bool trauma_os_tick { get; set; }
        public bool trauma_blunt_os_tick { get; set; }
        public string trauma_blunt_os { get; set; }
        public bool trauma_penetrating_os_tick { get; set; }
        public string trauma_penetrating_os { get; set; }
        public bool trauma_others_os_tick { get; set; }
        public string trauma_others_os { get; set; }
        public bool treatment_od_tick { get; set; }
        public bool treatment_medical_od_tick { get; set; }
        public string treatment_medical_od { get; set; }
        public bool treatment_surgical_od_tick { get; set; }
        public string treatment_surgical_od { get; set; }
        public bool treatment_donotknow_od_tick { get; set; }
        public string treatment_donotknow_od { get; set; }
        public bool treatment_os_tick { get; set; }
        public bool treatment_medical_os_tick { get; set; }
        public string treatment_medical_os { get; set; }
        public bool treatment_surgical_os_tick { get; set; }
        public string treatment_surgical_os { get; set; }
        public bool treatment_donotknow_os_tick { get; set; }
        public string treatment_donotknow_os { get; set; }
        public string treatment_remarks_od { get; set; }
        public string treatment_remarks_os { get; set; }
        public bool surg_od_tick { get; set; }
        public bool surg_glaucoma_od_tick { get; set; }
        public string surg_glaucoma_od_no { get; set; }
        public string surg_glaucoma_od_time { get; set; }
        public bool surg_cataract_od_tick { get; set; }
        public string surg_cataract_od_no { get; set; }
        public string surg_cataract_od_time { get; set; }
        public bool surg_retina_od_tick { get; set; }
        public string surg_retina_od_no { get; set; }
        public string surg_retina_od_time { get; set; }
        public bool surg_squint_od_tick { get; set; }
        public string surg_squint_od_no { get; set; }
        public string surg_squint_od_time { get; set; }
        public bool surg_corneal_od_tick { get; set; }
        public string surg_corneal_od_no { get; set; }
        public string surg_corneal_od_time { get; set; }
        public bool surg_opalrela_od_tick { get; set; }
        public string surg_opalrela_od_no { get; set; }
        public string surg_opalrela_od_time { get; set; }
        public bool surg_uveal_od_tick { get; set; }
        public string surg_uveal_od_no { get; set; }
        public string surg_uveal_od_time { get; set; }
        public bool surg_neuroopthamalic_od_tick { get; set; }
        public string surg_neuroopthamalic_od_no { get; set; }
        public string surg_neuroopthamalic_od_time { get; set; }
        public bool surg_others_od_tick { get; set; }
        public string surg_others_od_no { get; set; }
        public string surg_others_od_time { get; set; }
        public bool surg_os_tick { get; set; }
        public bool surg_glaucoma_os_tick { get; set; }
        public string surg_glaucoma_os_no { get; set; }
        public string surg_glaucoma_os_time { get; set; }
        public bool surg_cataract_os_tick { get; set; }
        public string surg_cataract_os_no { get; set; }
        public string surg_cataract_os_time { get; set; }
        public bool surg_retina_os_tick { get; set; }
        public string surg_retina_os_no { get; set; }
        public string surg_retina_os_time { get; set; }
        public bool surg_squint_os_tick { get; set; }
        public string surg_squint_os_no { get; set; }
        public string surg_squint_os_time { get; set; }
        public bool surg_corneal_os_tick { get; set; }
        public string surg_corneal_os_no { get; set; }
        public string surg_corneal_os_time { get; set; }
        public bool surg_opalrela_os_tick { get; set; }
        public string surg_opalrela_os_no { get; set; }
        public string surg_opalrela_os_time { get; set; }
        public bool surg_uveal_os_tick { get; set; }
        public string surg_uveal_os_no { get; set; }
        public string surg_uveal_os_time { get; set; }
        public bool surg_neuroopthamalic_os_tick { get; set; }
        public string surg_neuroopthamalic_os_no { get; set; }
        public string surg_neuroopthamalic_os_time { get; set; }
        public bool surg_others_os_tick { get; set; }
        public string surg_others_os_no { get; set; }
        public string surg_others_os_time { get; set; }
        public string surg_remarks_od { get; set; }
        public string surg_remarks_os { get; set; }
        public bool systill_od_tick { get; set; }
        public bool systill_hyper_od_tick { get; set; }
        public string systill_hyper_od { get; set; }
        public bool systill_diab_od_tick { get; set; }
        public string systill_diab_od { get; set; }
        public bool systill_astha_od_tick { get; set; }
        public string systill_astha_od { get; set; }
        public bool systill_cardc_od_tick { get; set; }
        public string systill_cardc_od { get; set; }
        public bool systill_thy_od_tick { get; set; }
        public string systill_thy_od { get; set; }
        public bool systill_cereb_od_tick { get; set; }
        public string systill_cereb_od { get; set; }
        public bool systill_hyperlipi_od_tick { get; set; }
        public string systill_hyperlipi_od { get; set; }
        public bool systill_kidney_od_tick { get; set; }
        public string systill_kidney_od { get; set; }
        public bool systill_anemia_od_tick { get; set; }
        public string systill_anemia_od { get; set; }
        public bool systill_eyeprob_od_tick { get; set; }
        public string systill_eyeprob_od { get; set; }
        public bool systill_rheu_od_tick { get; set; }
        public string systill_rheu_od { get; set; }
        public bool systill_inf_od_tick { get; set; }
        public string systill_inf_od { get; set; }
        public bool systill_others_od_tick { get; set; }
        public string systill_others_od { get; set; }
        public bool systill_os_tick { get; set; }
        public bool systill_hyper_os_tick { get; set; }
        public string systill_hyper_os { get; set; }
        public bool systill_diab_os_tick { get; set; }
        public string systill_diab_os { get; set; }
        public bool systill_astha_os_tick { get; set; }
        public string systill_astha_os { get; set; }
        public bool systill_cardc_os_tick { get; set; }
        public string systill_cardc_os { get; set; }
        public bool systill_thy_os_tick { get; set; }
        public string systill_thy_os { get; set; }
        public bool systill_cereb_os_tick { get; set; }
        public string systill_cereb_os { get; set; }
        public bool systill_hyperlipi_os_tick { get; set; }
        public string systill_hyperlipi_os { get; set; }
        public bool systill_kidney_os_tick { get; set; }
        public string systill_kidney_os { get; set; }
        public bool systill_anemia_os_tick { get; set; }
        public string systill_anemia_os { get; set; }
        public bool systill_eyeprob_os_tick { get; set; }
        public string systill_eyeprob_os { get; set; }
        public bool systill_rheu_os_tick { get; set; }
        public string systill_rheu_os { get; set; }
        public bool systill_inf_os_tick { get; set; }
        public string systill_inf_os { get; set; }
        public bool systill_others_os_tick { get; set; }
        public string systill_others_os { get; set; }
        public string systill_medi_od { get; set; }
        public string systill_medi_os { get; set; }
        public string systill_remarks_od { get; set; }
        public string systill_remarks_os { get; set; }
        public bool hisofstre_od_tick { get; set; }
        public bool hisofstre_oral_od_tick { get; set; }
        public string hisofstre_oral_od { get; set; }
        public bool hisofstre_injectsys_od_tick { get; set; }
        public string hisofstre_injectsys_od { get; set; }
        public bool hisofstre_injectperi_od_tick { get; set; }
        public string hisofstre_injectperi_od { get; set; }
        public bool hisofstre_eyedrop_od_tick { get; set; }
        public string hisofstre_eyedrop_od { get; set; }
        public bool hisofstre_skincr_od_tick { get; set; }
        public string hisofstre_skincr_od { get; set; }
        public bool hisofstre_others_od_tick { get; set; }
        public string hisofstre_others_od { get; set; }
        public bool hisofstre_os_tick { get; set; }
        public bool hisofstre_oral_os_tick { get; set; }
        public string hisofstre_oral_os { get; set; }
        public bool hisofstre_injectsys_os_tick { get; set; }
        public string hisofstre_injectsys_os { get; set; }
        public bool hisofstre_injectperi_os_tick { get; set; }
        public string hisofstre_injectperi_os { get; set; }
        public bool hisofstre_eyedrop_os_tick { get; set; }
        public string hisofstre_eyedrop_os { get; set; }
        public bool hisofstre_skincr_os_tick { get; set; }
        public string hisofstre_skincr_os { get; set; }
        public bool hisofstre_others_os_tick { get; set; }
        public string hisofstre_others_os { get; set; }
        public int famhis_od_tick { get; set; }
        public int famhis_glaucoma_od_tick { get; set; }
        public string famhis_glaucoma_od { get; set; }
        public int famhis_cataract_od_tick { get; set; }
        public string famhis_cataract_od { get; set; }
        public int famhis_retina_od_tick { get; set; }
        public string famhis_retina_od { get; set; }
        public int famhis_squint_od_tick { get; set; }
        public string famhis_squint_od { get; set; }
        public int famhis_corneal_od_tick { get; set; }
        public string famhis_corneal_od { get; set; }
        public int famhis_opalrela_od_tick { get; set; }
        public string famhis_opalrela_od { get; set; }
        public int famhis_uveal_od_tick { get; set; }
        public string famhis_uveal_od { get; set; }
        public int famhis_neuro_od_tick { get; set; }
        public string famhis_neuro_od { get; set; }
        public int famhis_others_od_tick { get; set; }
        public string famhis_others_od { get; set; }
        public int famhis_os_tick { get; set; }
        public int famhis_glaucoma_os_tick { get; set; }
        public string famhis_glaucoma_os { get; set; }
        public int famhis_cataract_os_tick { get; set; }
        public string famhis_cataract_os { get; set; }
        public int famhis_retina_os_tick { get; set; }
        public string famhis_retina_os { get; set; }
        public int famhis_squint_os_tick { get; set; }
        public string famhis_squint_os { get; set; }
        public int famhis_corneal_os_tick { get; set; }
        public string famhis_corneal_os { get; set; }
        public int famhis_opalrela_os_tick { get; set; }
        public string famhis_opalrela_os { get; set; }
        public int famhis_uveal_os_tick { get; set; }
        public string famhis_uveal_os { get; set; }
        public int famhis_neuro_os_tick { get; set; }
        public string famhis_neuro_os { get; set; }
        public int famhis_others_os_tick { get; set; }
        public string famhis_others_os { get; set; }
        public string fam_reltosub_od { get; set; }
        public string fam_reltosub_os { get; set; }
        public bool famhisofeye_od_tick { get; set; }
        public string famhisofeye_od { get; set; }
        public bool famhisofeye_os_tick { get; set; }
        public string famhisofeye_os { get; set; }
        public bool allerg_od_tick { get; set; }
        public string allerg_od { get; set; }
        public bool allerg_os_tick { get; set; }
        public string allerg_os { get; set; }
    }

    public class Past_Eye_HistorySelectAll_dt
    {
        public string mrdno { get; set; }
        public int hospid { get; set; }
        public DateTime ddate { get; set; }
        public bool eyeproblem_od_tick { get; set; }
        public bool eyeproblem_glaucoma_od_tick { get; set; }
        public string eyeproblem_glaucoma_od { get; set; }
        public bool eyeproblem_cataract_od_tick { get; set; }
        public string eyeproblem_cataract_od { get; set; }
        public bool eyeproblem_retina_od_tick { get; set; }
        public string eyeproblem_retina_od { get; set; }
        public bool eyeproblem_squint_od_tick { get; set; }
        public string eyeproblem_squint_od { get; set; }
        public bool eyeproblem_corneal_od_tick { get; set; }
        public string eyeproblem_corneal_od { get; set; }
        public bool eyeproblem_opalrelated_od_tick { get; set; }
        public string eyeproblem_opalrelated_od { get; set; }
        public bool eyeproblem_uveal_od_tick { get; set; }
        public string eyeproblem_uveal_od { get; set; }
        public bool eyeproblem_neuro_od_tick { get; set; }
        public string eyeproblem_neuro_od { get; set; }
        public bool eyeproblem_others_od_tick { get; set; }
        public string eyeproblem_others_od { get; set; }
        public bool eyeproblem_os_tick { get; set; }
        public bool eyeproblem_glaucoma_os_tick { get; set; }
        public string eyeproblem_glaucoma_os { get; set; }
        public bool eyeproblem_cataract_os_tick { get; set; }
        public string eyeproblem_cataract_os { get; set; }
        public bool eyeproblem_retina_os_tick { get; set; }
        public string eyeproblem_retina_os { get; set; }
        public bool eyeproblem_squint_os_tick { get; set; }
        public string eyeproblem_squint_os { get; set; }
        public bool eyeproblem_corneal_os_tick { get; set; }
        public string eyeproblem_corneal_os { get; set; }
        public bool eyeproblem_opalrelated_os_tick { get; set; }
        public string eyeproblem_opalrelated_os { get; set; }
        public bool eyeproblem_uveal_os_tick { get; set; }
        public string eyeproblem_uveal_os { get; set; }
        public bool eyeproblem_neuro_os_tick { get; set; }
        public string eyeproblem_neuro_os { get; set; }
        public bool eyeproblem_others_os_tick { get; set; }
        public string eyeproblem_others_os { get; set; }
        public string eyeprob_remarks_od { get; set; }
        public string eyeprob_remarks_os { get; set; }
        public bool trauma_od_tick { get; set; }
        public bool trauma_blunt_od_tick { get; set; }
        public string trauma_blunt_od { get; set; }
        public bool trauma_penetrating_od_tick { get; set; }
        public string trauma_penetrating_od { get; set; }
        public bool trauma_others_od_tick { get; set; }
        public string trauma_others_od { get; set; }
        public bool trauma_os_tick { get; set; }
        public bool trauma_blunt_os_tick { get; set; }
        public string trauma_blunt_os { get; set; }
        public bool trauma_penetrating_os_tick { get; set; }
        public string trauma_penetrating_os { get; set; }
        public bool trauma_others_os_tick { get; set; }
        public string trauma_others_os { get; set; }
        public bool treatment_od_tick { get; set; }
        public bool treatment_medical_od_tick { get; set; }
        public string treatment_medical_od { get; set; }
        public bool treatment_surgical_od_tick { get; set; }
        public string treatment_surgical_od { get; set; }
        public bool treatment_donotknow_od_tick { get; set; }
        public string treatment_donotknow_od { get; set; }
        public bool treatment_os_tick { get; set; }
        public bool treatment_medical_os_tick { get; set; }
        public string treatment_medical_os { get; set; }
        public bool treatment_surgical_os_tick { get; set; }
        public string treatment_surgical_os { get; set; }
        public bool treatment_donotknow_os_tick { get; set; }
        public string treatment_donotknow_os { get; set; }
        public string treatment_remarks_od { get; set; }
        public string treatment_remarks_os { get; set; }
        public bool surg_od_tick { get; set; }
        public bool surg_glaucoma_od_tick { get; set; }
        public string surg_glaucoma_od_no { get; set; }
        public string surg_glaucoma_od_time { get; set; }
        public bool surg_cataract_od_tick { get; set; }
        public string surg_cataract_od_no { get; set; }
        public string surg_cataract_od_time { get; set; }
        public bool surg_retina_od_tick { get; set; }
        public string surg_retina_od_no { get; set; }
        public string surg_retina_od_time { get; set; }
        public bool surg_squint_od_tick { get; set; }
        public string surg_squint_od_no { get; set; }
        public string surg_squint_od_time { get; set; }
        public bool surg_corneal_od_tick { get; set; }
        public string surg_corneal_od_no { get; set; }
        public string surg_corneal_od_time { get; set; }
        public bool surg_opalrela_od_tick { get; set; }
        public string surg_opalrela_od_no { get; set; }
        public string surg_opalrela_od_time { get; set; }
        public bool surg_uveal_od_tick { get; set; }
        public string surg_uveal_od_no { get; set; }
        public string surg_uveal_od_time { get; set; }
        public bool surg_neuroopthamalic_od_tick { get; set; }
        public string surg_neuroopthamalic_od_no { get; set; }
        public string surg_neuroopthamalic_od_time { get; set; }
        public bool surg_others_od_tick { get; set; }
        public string surg_others_od_no { get; set; }
        public string surg_others_od_time { get; set; }
        public bool surg_os_tick { get; set; }
        public bool surg_glaucoma_os_tick { get; set; }
        public string surg_glaucoma_os_no { get; set; }
        public string surg_glaucoma_os_time { get; set; }
        public bool surg_cataract_os_tick { get; set; }
        public string surg_cataract_os_no { get; set; }
        public string surg_cataract_os_time { get; set; }
        public bool surg_retina_os_tick { get; set; }
        public string surg_retina_os_no { get; set; }
        public string surg_retina_os_time { get; set; }
        public bool surg_squint_os_tick { get; set; }
        public string surg_squint_os_no { get; set; }
        public string surg_squint_os_time { get; set; }
        public bool surg_corneal_os_tick { get; set; }
        public string surg_corneal_os_no { get; set; }
        public string surg_corneal_os_time { get; set; }
        public bool surg_opalrela_os_tick { get; set; }
        public string surg_opalrela_os_no { get; set; }
        public string surg_opalrela_os_time { get; set; }
        public bool surg_uveal_os_tick { get; set; }
        public string surg_uveal_os_no { get; set; }
        public string surg_uveal_os_time { get; set; }
        public bool surg_neuroopthamalic_os_tick { get; set; }
        public string surg_neuroopthamalic_os_no { get; set; }
        public string surg_neuroopthamalic_os_time { get; set; }
        public bool surg_others_os_tick { get; set; }
        public string surg_others_os_no { get; set; }
        public string surg_others_os_time { get; set; }
        public string surg_remarks_od { get; set; }
        public string surg_remarks_os { get; set; }
        public bool systill_od_tick { get; set; }
        public bool systill_hyper_od_tick { get; set; }
        public string systill_hyper_od { get; set; }
        public bool systill_diab_od_tick { get; set; }
        public string systill_diab_od { get; set; }
        public bool systill_astha_od_tick { get; set; }
        public string systill_astha_od { get; set; }
        public bool systill_cardc_od_tick { get; set; }
        public string systill_cardc_od { get; set; }
        public bool systill_thy_od_tick { get; set; }
        public string systill_thy_od { get; set; }
        public bool systill_cereb_od_tick { get; set; }
        public string systill_cereb_od { get; set; }
        public bool systill_hyperlipi_od_tick { get; set; }
        public string systill_hyperlipi_od { get; set; }
        public bool systill_kidney_od_tick { get; set; }
        public string systill_kidney_od { get; set; }
        public bool systill_anemia_od_tick { get; set; }
        public string systill_anemia_od { get; set; }
        public bool systill_eyeprob_od_tick { get; set; }
        public string systill_eyeprob_od { get; set; }
        public bool systill_rheu_od_tick { get; set; }
        public string systill_rheu_od { get; set; }
        public bool systill_inf_od_tick { get; set; }
        public string systill_inf_od { get; set; }
        public bool systill_others_od_tick { get; set; }
        public string systill_others_od { get; set; }
        public bool systill_os_tick { get; set; }
        public bool systill_hyper_os_tick { get; set; }
        public string systill_hyper_os { get; set; }
        public bool systill_diab_os_tick { get; set; }
        public string systill_diab_os { get; set; }
        public bool systill_astha_os_tick { get; set; }
        public string systill_astha_os { get; set; }
        public bool systill_cardc_os_tick { get; set; }
        public string systill_cardc_os { get; set; }
        public bool systill_thy_os_tick { get; set; }
        public string systill_thy_os { get; set; }
        public bool systill_cereb_os_tick { get; set; }
        public string systill_cereb_os { get; set; }
        public bool systill_hyperlipi_os_tick { get; set; }
        public string systill_hyperlipi_os { get; set; }
        public bool systill_kidney_os_tick { get; set; }
        public string systill_kidney_os { get; set; }
        public bool systill_anemia_os_tick { get; set; }
        public string systill_anemia_os { get; set; }
        public bool systill_eyeprob_os_tick { get; set; }
        public string systill_eyeprob_os { get; set; }
        public bool systill_rheu_os_tick { get; set; }
        public string systill_rheu_os { get; set; }
        public bool systill_inf_os_tick { get; set; }
        public string systill_inf_os { get; set; }
        public bool systill_others_os_tick { get; set; }
        public string systill_others_os { get; set; }
        public string systill_medi_od { get; set; }
        public string systill_medi_os { get; set; }
        public string systill_remarks_od { get; set; }
        public string systill_remarks_os { get; set; }
        public bool hisofstre_od_tick { get; set; }
        public bool hisofstre_oral_od_tick { get; set; }
        public string hisofstre_oral_od { get; set; }
        public bool hisofstre_injectsys_od_tick { get; set; }
        public string hisofstre_injectsys_od { get; set; }
        public bool hisofstre_injectperi_od_tick { get; set; }
        public string hisofstre_injectperi_od { get; set; }
        public bool hisofstre_eyedrop_od_tick { get; set; }
        public string hisofstre_eyedrop_od { get; set; }
        public bool hisofstre_skincr_od_tick { get; set; }
        public string hisofstre_skincr_od { get; set; }
        public bool hisofstre_others_od_tick { get; set; }
        public string hisofstre_others_od { get; set; }
        public bool hisofstre_os_tick { get; set; }
        public bool hisofstre_oral_os_tick { get; set; }
        public string hisofstre_oral_os { get; set; }
        public bool hisofstre_injectsys_os_tick { get; set; }
        public string hisofstre_injectsys_os { get; set; }
        public bool hisofstre_injectperi_os_tick { get; set; }
        public string hisofstre_injectperi_os { get; set; }
        public bool hisofstre_eyedrop_os_tick { get; set; }
        public string hisofstre_eyedrop_os { get; set; }
        public bool hisofstre_skincr_os_tick { get; set; }
        public string hisofstre_skincr_os { get; set; }
        public bool hisofstre_others_os_tick { get; set; }
        public string hisofstre_others_os { get; set; }
        public string famhis_od_tick { get; set; }
        public string famhis_glaucoma_od_tick { get; set; }
        public string famhis_glaucoma_od { get; set; }
        public string famhis_cataract_od_tick { get; set; }
        public string famhis_cataract_od { get; set; }
        public string famhis_retina_od_tick { get; set; }
        public string famhis_retina_od { get; set; }
        public string famhis_squint_od_tick { get; set; }
        public string famhis_squint_od { get; set; }
        public string famhis_corneal_od_tick { get; set; }
        public string famhis_corneal_od { get; set; }
        public string famhis_opalrela_od_tick { get; set; }
        public string famhis_opalrela_od { get; set; }
        public string famhis_uveal_od_tick { get; set; }
        public string famhis_uveal_od { get; set; }
        public string famhis_neuro_od_tick { get; set; }
        public string famhis_neuro_od { get; set; }
        public string famhis_others_od_tick { get; set; }
        public string famhis_others_od { get; set; }
        public string famhis_os_tick { get; set; }
        public string famhis_glaucoma_os_tick { get; set; }
        public string famhis_glaucoma_os { get; set; }
        public string famhis_cataract_os_tick { get; set; }
        public string famhis_cataract_os { get; set; }
        public string famhis_retina_os_tick { get; set; }
        public string famhis_retina_os { get; set; }
        public string famhis_squint_os_tick { get; set; }
        public string famhis_squint_os { get; set; }
        public string famhis_corneal_os_tick { get; set; }
        public string famhis_corneal_os { get; set; }
        public string famhis_opalrela_os_tick { get; set; }
        public string famhis_opalrela_os { get; set; }
        public string famhis_uveal_os_tick { get; set; }
        public string famhis_uveal_os { get; set; }
        public string famhis_neuro_os_tick { get; set; }
        public string famhis_neuro_os { get; set; }
        public string famhis_others_os_tick { get; set; }
        public string famhis_others_os { get; set; }
        public string fam_reltosub_od { get; set; }
        public string fam_reltosub_os { get; set; }
        public bool famhisofeye_od_tick { get; set; }
        public string famhisofeye_od { get; set; }
        public bool famhisofeye_os_tick { get; set; }
        public string famhisofeye_os { get; set; }
        public bool allerg_od_tick { get; set; }
        public string allerg_od { get; set; }
        public bool allerg_os_tick { get; set; }
        public string allerg_os { get; set; }
    }

    public class Past_Eye_HistoryInsert_dt
    {
        public string mrdno { get; set; }
        public DateTime ddate { get; set; }
        public int userid { get; set; }
        public DateTime biltime { get; set; }
        public int hospid { get; set; }
    }

    public class Past_Eye_HistoryUpdate_dt
    {
        public string mrdno { get; set; }
        public DateTime ddate { get; set; }
        public int userid { get; set; }
        public DateTime biltime { get; set; }
        public int hospid { get; set; }
    }

    public class Past_Eye_HistorySelect_dt
    {
        public int sn { get; set; }
        public string mrdno { get; set; }
        public DateTime ddate { get; set; }
        public int userid { get; set; }
        public DateTime biltime { get; set; }
        public int hospid { get; set; }
    }

    public class Past_Eye_HistoryDelete_dt
    {
        public string mrdno { get; set; }
    }
}