using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace medipro.api.Medipro.Models.NewModels.EyeDocs.PivotTitle
{
    public class OcularInvestigationDetailPivot_dt
    {
        public DateTime ddate { get; set; }
        public string mrdno { get; set; }
        public int clusterno { get; set; }
        public int kesid { get; set; }
        public string ocular_invest_od { get; set; }
        public string ocular_invest_media_tick { get; set; }
        public string ocular_invest_poor_tick { get; set; }
        public string ocular_invest_fixation_tick { get; set; }
        public string ocular_invest_other_tick { get; set; }
        public string ocular_invest_other_specify { get; set; }
        public string dry_eye_test_od { get; set; }
        public string dry_eye_test_os { get; set; }
        public string schirmer_test_od { get; set; }
        public string schirmer_od_media_tick { get; set; }
        public string schirmer_od_poor_tick { get; set; }
        public string schirmer_od_fixation_tick { get; set; }
        public string schirmer_od_other_tick { get; set; }
        public string schirmer_od_other_specify { get; set; }
        public string schirmer_test_os { get; set; }
        public string schirmer_os_media_tick { get; set; }
        public string schirmer_os_poor_tick { get; set; }
        public string schirmer_os_fixation_tick { get; set; }
        public string schirmer_os_other_tick { get; set; }
        public string schirmer_os_other_specify { get; set; }
        public string amsler_od { get; set; }
        public string amsler_od_specify { get; set; }
        public string amsler_od_media_tick { get; set; }
        public string amsler_od_poor_tick { get; set; }
        public string amsler_od_fixation_tick { get; set; }
        public string amsler_od_other_tick { get; set; }
        public string amsler_od_other_specify { get; set; }
        public string amsler_os { get; set; }
        public string amsler_os_specify { get; set; }
        public string amsler_os_media_tick { get; set; }
        public string amsler_os_poor_tick { get; set; }
        public string amsler_os_fixation_tick { get; set; }
        public string amsler_os_other_tick { get; set; }
        public string amsler_os_other_specify { get; set; }
        public string duchrome_od { get; set; }
        public string duchrome_od_specify { get; set; }
        public string duchrome_od_media_tick { get; set; }
        public string duchrome_od_poor_tick { get; set; }
        public string duchrome_od_fixation_tick { get; set; }
        public string duchrome_od_other_tick { get; set; }
        public string duchrome_od_other_specify { get; set; }
        public string duchrome_os { get; set; }
        public string duchrome_os_specify { get; set; }
        public string duchrome_os_media_tick { get; set; }
        public string duchrome_os_poor_tick { get; set; }
        public string duchrome_os_fixation_tick { get; set; }
        public string duchrome_os_other_tick { get; set; }
        public string duchrome_os_other_specify { get; set; }
        public string color_vision_od { get; set; }
        public string color_vision_od_specify { get; set; }
        public string color_vision_od_media_tick { get; set; }
        public string color_vision_od_poor_tick { get; set; }
        public string color_vision_od_fixation_tick { get; set; }
        public string color_vision_od_other_tick { get; set; }
        public string color_vision_od_other_specify { get; set; }
        public string color_vision_os { get; set; }
        public string color_vision_os_specify { get; set; }
        public string color_vision_os_media_tick { get; set; }
        public string color_vision_os_poor_tick { get; set; }
        public string color_vision_os_fixation_tick { get; set; }
        public string color_vision_os_other_tick { get; set; }
        public string color_vision_os_other_specify { get; set; }
        public string syring_prob_od { get; set; }
        public string syring_prob_od_specify { get; set; }
        public string syring_prob_od_media_tick { get; set; }
        public string syring_prob_od_poor_tick { get; set; }
        public string syring_prob_od_fixation_tick { get; set; }
        public string syring_prob_od_other_tick { get; set; }
        public string syring_prob_od_other_specify { get; set; }
        public string syring_prob_os { get; set; }
        public string syring_prob_os_specify { get; set; }
        public string syring_prob_os_media_tick { get; set; }
        public string syring_prob_os_poor_tick { get; set; }
        public string syring_prob_os_fixation_tick { get; set; }
        public string syring_prob_os_other_tick { get; set; }
        public string syring_prob_os_other_specify { get; set; }
        public string visualfield_od { get; set; }
        public string visualfield_od_media_tick { get; set; }
        public string visualfield_od_poor_tick { get; set; }
        public string visualfield_od_fixation_tick { get; set; }
        public string visualfield_od_other_tick { get; set; }
        public string visualfield_od_other_specify { get; set; }
        public string visualfield_od_test_duration { get; set; }
        public string visualfield_od_mean { get; set; }
        public string visualfield_od_psd { get; set; }
        public string visualfield_od_fix_error { get; set; }
        public string visualfield_od_false_pos { get; set; }
        public string visualfield_od_false_neg { get; set; }
        public string visualfield_od_fovea { get; set; }
        public string visualfield_od_comment { get; set; }
        public string visualfield_os { get; set; }
        public string visualfield_os_media_tick { get; set; }
        public string visualfield_os_poor_tick { get; set; }
        public string visualfield_os_fixation_tick { get; set; }
        public string visualfield_os_other_tick { get; set; }
        public string visualfield_os_other_specify { get; set; }
        public string visualfield_os_test_duration { get; set; }
        public string visualfield_os_mean { get; set; }
        public string visualfield_os_psd { get; set; }
        public string visualfield_os_fix_error { get; set; }
        public string visualfield_os_false_pos { get; set; }
        public string visualfield_os_false_neg { get; set; }
        public string visualfield_os_fovea { get; set; }
        public string visualfield_os_comment { get; set; }
        public string vf_interpretation_od { get; set; }
        public string vf_interpretation_option_od { get; set; }
        public string vf_interpretation_option_od_specify { get; set; }
        public string vf_interpretation_os { get; set; }
        public string vf_interpretation_option_os { get; set; }
        public string vf_interpretation_option_os_specify { get; set; }
        public string ant_seg_invest_od { get; set; }
        public string ant_seg_invest_od_media_tick { get; set; }
        public string ant_seg_invest_od_poor_tick { get; set; }
        public string ant_seg_invest_od_fixation_tick { get; set; }
        public string ant_seg_invest_od_other_tick { get; set; }
        public string ant_seg_invest_od_other_specify { get; set; }
        public string cor_topography_od { get; set; }
        public string cor_topography_od_oct { get; set; }
        public string cor_topography_od_oct_k1 { get; set; }
        public string cor_topography_od_oct_k2 { get; set; }
        public string cor_topography_od_pachy { get; set; }
        public string cor_topography_od_pachy_k1 { get; set; }
        public string cor_topography_od_pachy_k2 { get; set; }
        public string cor_topography_od_media_tick { get; set; }
        public string cor_topography_od_poor_tick { get; set; }
        public string cor_topography_od_fixation_tick { get; set; }
        public string cor_topography_od_other_tick { get; set; }
        public string cor_topography_od_other_specify { get; set; }
        public string cor_topography_os { get; set; }
        public string cor_topography_os_oct { get; set; }
        public string cor_topography_os_oct_k1 { get; set; }
        public string cor_topography_os_oct_k2 { get; set; }
        public string cor_topography_os_pachy { get; set; }
        public string cor_topography_os_pachy_k1 { get; set; }
        public string cor_topography_os_pachy_k2 { get; set; }
        public string cor_topography_os_media_tick { get; set; }
        public string cor_topography_os_poor_tick { get; set; }
        public string cor_topography_os_fixation_tick { get; set; }
        public string cor_topography_os_other_tick { get; set; }
        public string cor_topography_os_other_specify { get; set; }
        public string cor_topo_interpretation_od { get; set; }
        public string cor_topo_interpretation_od_specify { get; set; }
        public string cor_topo_interpretation_os { get; set; }
        public string cor_topo_interpretation_os_specify { get; set; }
        public string biometry_od { get; set; }
        public string biometry_od_k1 { get; set; }
        public string biometry_od_k2 { get; set; }
        public string biometry_od_axial_length { get; set; }
        public string biometry_od_ac { get; set; }
        public string biometry_od_lens { get; set; }
        public string biometry_od_iol { get; set; }
        public string biometry_od_constant { get; set; }
        public string biometry_od_iol_power { get; set; }
        public string biometry_od_media_tick { get; set; }
        public string biometry_od_poor_tick { get; set; }
        public string biometry_od_fixation_tick { get; set; }
        public string biometry_od_other_tick { get; set; }
        public string biometry_od_other_specify { get; set; }
        public string biometry_os { get; set; }
        public string biometry_os_k1 { get; set; }
        public string biometry_os_k2 { get; set; }
        public string biometry_os_axial_length { get; set; }
        public string biometry_os_ac { get; set; }
        public string biometry_os_lens { get; set; }
        public string biometry_os_iol { get; set; }
        public string biometry_os_constant { get; set; }
        public string biometry_os_iol_power { get; set; }
        public string biometry_os_media_tick { get; set; }
        public string biometry_os_poor_tick { get; set; }
        public string biometry_os_fixation_tick { get; set; }
        public string biometry_os_other_tick { get; set; }
        public string biometry_os_other_specify { get; set; }
        public string ant_seg_oct_od { get; set; }
        public string ant_seg_oct_od_shaffer { get; set; }
        public string ant_seg_oct_od_iris1 { get; set; }
        public string ant_seg_oct_od_iris2 { get; set; }
        public string ant_seg_oct_od_acdepth { get; set; }
        public string ant_seg_oct_od_acwidth { get; set; }
        public string ant_seg_oct_od_lens_vault { get; set; }
        public string ant_seg_oct_od_ara { get; set; }
        public string ant_seg_oct_od_aod { get; set; }
        public string ant_seg_oct_od_aod750 { get; set; }
        public string ant_seg_oct_od_tisa { get; set; }
        public string ant_seg_oct_od_tia { get; set; }
        public string ant_seg_oct_od_media_tick { get; set; }
        public string ant_seg_oct_od_poor_tick { get; set; }
        public string ant_seg_oct_od_fixation_tick { get; set; }
        public string ant_seg_oct_od_other_tick { get; set; }
        public string ant_seg_oct_od_other_specify { get; set; }
        public string ant_seg_oct_os { get; set; }
        public string ant_seg_oct_os_shaffer { get; set; }
        public string ant_seg_oct_os_iris1 { get; set; }
        public string ant_seg_oct_os_iris2 { get; set; }
        public string ant_seg_oct_os_acdepth { get; set; }
        public string ant_seg_oct_os_acwidth { get; set; }
        public string ant_seg_oct_os_lens_vault { get; set; }
        public string ant_seg_oct_os_ara { get; set; }
        public string ant_seg_oct_os_aod { get; set; }
        public string ant_seg_oct_os_aod750 { get; set; }
        public string ant_seg_oct_os_tisa { get; set; }
        public string ant_seg_oct_os_tia { get; set; }
        public string ant_seg_oct_os_media_tick { get; set; }
        public string ant_seg_oct_os_poor_tick { get; set; }
        public string ant_seg_oct_os_fixation_tick { get; set; }
        public string ant_seg_oct_os_other_tick { get; set; }
        public string ant_seg_oct_os_other_specify { get; set; }
        public string asoct_interpretation_od { get; set; }
        public string asoct_interpretation_od_specify { get; set; }
        public string asoct_interpretation_os { get; set; }
        public string asoct_interpretation_os_specify { get; set; }
        public string pos_seg_invest_od { get; set; }
        public string pos_seg_invest_od_media_tick { get; set; }
        public string pos_seg_invest_od_poor_tick { get; set; }
        public string pos_seg_invest_od_fixation_tick { get; set; }
        public string pos_seg_invest_od_other_tick { get; set; }
        public string pos_seg_invest_od_other_specify { get; set; }
        public string fundus_od { get; set; }
        public string fundus_od_media_tick { get; set; }
        public string fundus_od_poor_tick { get; set; }
        public string fundus_od_fixation_tick { get; set; }
        public string fundus_od_other_tick { get; set; }
        public string fundus_od_other_specify { get; set; }
        public string fundus_os { get; set; }
        public string fundus_os_media_tick { get; set; }
        public string fundus_os_poor_tick { get; set; }
        public string fundus_os_fixation_tick { get; set; }
        public string fundus_os_other_tick { get; set; }
        public string fundus_os_other_specify { get; set; }
        public string fundus_interpretation_od { get; set; }
        public string fundus_interpretation_od_specify { get; set; }
        public string fundus_interpretation_os { get; set; }
        public string fundus_interpretation_os_specify { get; set; }
        public string disc_od { get; set; }
        public string disc_od_media_tick { get; set; }
        public string disc_od_poor_tick { get; set; }
        public string disc_od_fixation_tick { get; set; }
        public string disc_od_other_tick { get; set; }
        public string disc_od_other_specify { get; set; }
        public string disc_os { get; set; }
        public string disc_os_media_tick { get; set; }
        public string disc_os_poor_tick { get; set; }
        public string disc_os_fixation_tick { get; set; }
        public string disc_os_other_tick { get; set; }
        public string disc_os_other_specify { get; set; }
        public string disc_interpretation_od { get; set; }
        public string disc_interpretation_od_specify { get; set; }
        public string disc_interpretation_os { get; set; }
        public string disc_interpretation_os_specify { get; set; }
        public string posterior_oct_od { get; set; }
        public string posterior_oct_od_media_tick { get; set; }
        public string posterior_oct_od_poor_tick { get; set; }
        public string posterior_oct_od_fixation_tick { get; set; }
        public string posterior_oct_od_other_tick { get; set; }
        public string posterior_oct_od_other_specify { get; set; }
        public string posterior_oct_od_sig_strength { get; set; }
        public string posterior_oct_od_tot_rnfl { get; set; }
        public string posterior_oct_od_sup_rnfl { get; set; }
        public string posterior_oct_od_inf_rnfl { get; set; }
        public string posterior_oct_od_nas_rnfl { get; set; }
        public string posterior_oct_od_temp_rnfl { get; set; }
        public string posterior_oct_od_avg_thick { get; set; }
        public string posterior_oct_od_vol { get; set; }
        public string posterior_oct_os { get; set; }
        public string posterior_oct_os_media_tick { get; set; }
        public string posterior_oct_os_poor_tick { get; set; }
        public string posterior_oct_os_fixation_tick { get; set; }
        public string posterior_oct_os_other_tick { get; set; }
        public string posterior_oct_os_other_specify { get; set; }
        public string posterior_oct_os_sig_strength { get; set; }
        public string posterior_oct_os_tot_rnfl { get; set; }
        public string posterior_oct_os_sup_rnfl { get; set; }
        public string posterior_oct_os_inf_rnfl { get; set; }
        public string posterior_oct_os_nas_rnfl { get; set; }
        public string posterior_oct_os_temp_rnfl { get; set; }
        public string posterior_oct_os_avg_thick { get; set; }
        public string posterior_oct_os_vol { get; set; }
        public string posterior_oct_interpretation_od { get; set; }
        public string posterior_oct_interpretation_od_specify { get; set; }
        public string posterior_oct_interpretation_os { get; set; }
        public string posterior_oct_interpretation_os_specify { get; set; }
        public string remarks { get; set; }

    }
}