using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace medipro.api.Medipro.Models.NewModels.EyeDocs.PivotTitle
{
    public class OcularExaminationDetailPivot_dt
    {
        public DateTime ddate { get; set; }
        public string mrdno { get; set; }
        public int clusterno { get; set; }
        public int kesid { get; set; }
        public string ant_segment { get; set; }
        public string proptosis_od { get; set; }
        public string proptosis_os { get; set; }
        public string eom_od { get; set; }
        public string eom_starbismus_od_tick { get; set; }
        public string eom_esotropia_od_tick { get; set; }
        public string eom_exotropia_od_tick { get; set; }
        public string eom_hypertropia_od_tick { get; set; }
        public string eom_hypotropia_od_tick { get; set; }
        public string eom_esophoria_od_tick { get; set; }
        public string eom_exophoria_od_tick { get; set; }
        public string eom_hyperphoria_od_tick { get; set; }
        public string eom_hypophoria_od_tick { get; set; }
        public string eom_nystag_od_tick { get; set; }
        public string eom_other_od_tick { get; set; }
        public string eom_other_specify_od { get; set; }
        public string eom_os { get; set; }
        public string eom_starbismus_os_tick { get; set; }
        public string eom_esotropia_os_tick { get; set; }
        public string eom_exotropia_os_tick { get; set; }
        public string eom_hypertropia_os_tick { get; set; }
        public string eom_hypotropia_os_tick { get; set; }
        public string eom_esophoria_os_tick { get; set; }
        public string eom_exophoria_os_tick { get; set; }
        public string eom_hyperphoria_os_tick { get; set; }
        public string eom_hypophoria_os_tick { get; set; }
        public string eom_nystag_os_tick { get; set; }
        public string eom_other_os_tick { get; set; }
        public string eom_other_specify_os { get; set; }
        public string lid_od { get; set; }
        public string lid_od_dermatochalasis_tick { get; set; }
        public string lid_od_xanthelasma_tick { get; set; }
        public string lid_od_poliosis_tick { get; set; }
        public string lid_od_ptosis_tick { get; set; }
        public string lid_od_entropin_tick { get; set; }
        public string lid_od_ectoprion_tick { get; set; }
        public string lid_od_chalazion_tick { get; set; }
        public string lid_od_stye_tick { get; set; }
        public string lid_od_lid_abscess_tick { get; set; }
        public string lid_od_laceration_tick { get; set; }
        public string lid_od_others_tick { get; set; }
        public string lid_od_others_specify { get; set; }
        public string lid_os { get; set; }
        public string lid_os_dermatochalasis_tick { get; set; }
        public string lid_os_xanthelasma_tick { get; set; }
        public string lid_os_poliosis_tick { get; set; }
        public string lid_os_ptosis_tick { get; set; }
        public string lid_os_entropin_tick { get; set; }
        public string lid_os_ectoprion_tick { get; set; }
        public string lid_os_chalazion_tick { get; set; }
        public string lid_os_stye_tick { get; set; }
        public string lid_os_lid_abscess_tick { get; set; }
        public string lid_os_laceration_tick { get; set; }
        public string lid_os_others_tick { get; set; }
        public string lid_os_others_specify { get; set; }
        public string conjuc_od { get; set; }
        public string conjuc_od_pterygium_tick { get; set; }
        public string conjuc_od_pterygium_specify { get; set; }
        public string conjuc_od_pinguecula_tick { get; set; }
        public string conjuc_od_pinguecula_specify { get; set; }
        public string conjuc_od_congestion_tick { get; set; }
        public string conjuc_od_nevus_tick { get; set; }
        public string conjuc_od_bleb_tick { get; set; }
        public string conjuc_od_laceration_tick { get; set; }
        public string conjuc_od_steriod_tick { get; set; }
        public string conjuc_od_others_tick { get; set; }
        public string conjuc_od_others_specify { get; set; }
        public string conjuc_os { get; set; }
        public string conjuc_os_pterygium_tick { get; set; }
        public string conjuc_os_pterygium_specify { get; set; }
        public string conjuc_os_pinguecula_tick { get; set; }
        public string conjuc_os_pinguecula_specify { get; set; }
        public string conjuc_os_congestion_tick { get; set; }
        public string conjuc_os_nevus_tick { get; set; }
        public string conjuc_os_bleb_tick { get; set; }
        public string conjuc_os_laceration_tick { get; set; }
        public string conjuc_os_steriod_tick { get; set; }
        public string conjuc_os_others_tick { get; set; }
        public string conjuc_os_others_specify { get; set; }
        public string sclera_od { get; set; }
        public string sclera_od_staphyloma_tick { get; set; }
        public string sclera_od_icterus_tick { get; set; }
        public string sclera_od_thinning_tick { get; set; }
        public string sclera_od_melting_tick { get; set; }
        public string sclera_od_laceration_tick { get; set; }
        public string sclera_od_others_tick { get; set; }
        public string sclera_od_others_specify { get; set; }
        public string sclera_os { get; set; }
        public string sclera_os_staphyloma_tick { get; set; }
        public string sclera_os_icterus_tick { get; set; }
        public string sclera_os_thinning_tick { get; set; }
        public string sclera_os_melting_tick { get; set; }
        public string sclera_os_laceration_tick { get; set; }
        public string sclera_os_others_tick { get; set; }
        public string sclera_os_others_specify { get; set; }
        public string cornea_od { get; set; }
        public string cornea_od_scar_tick { get; set; }
        public string cornea_od_vascularation_tick { get; set; }
        public string cornea_od_coneal_edema_tick { get; set; }
        public string cornea_od_abrasion_tick { get; set; }
        public string cornea_od_keratic_tick { get; set; }
        public string cornea_od_others_tick { get; set; }
        public string cornea_od_others_specify { get; set; }
        public string cornea_os { get; set; }
        public string cornea_os_scar_tick { get; set; }
        public string cornea_os_vascularation_tick { get; set; }
        public string cornea_os_coneal_edema_tick { get; set; }
        public string cornea_os_abrasion_tick { get; set; }
        public string cornea_os_keratic_tick { get; set; }
        public string cornea_os_others_tick { get; set; }
        public string cornea_os_others_specify { get; set; }
        public string antcham_od { get; set; }
        public string antcham_cells_od_tick { get; set; }
        public string antcham_cells_od { get; set; }
        public string antcham_flare_od_tick { get; set; }
        public string antcham_flare_od { get; set; }
        public string antcham_hyphema_od_tick { get; set; }
        public string antcham_hypopyon_od_tick { get; set; }
        public string antcham_emulsified_od_tick { get; set; }
        public string antcham_vitreous_od_tick { get; set; }
        public string antcham_od_others_tick { get; set; }
        public string antcham_od_others_specify { get; set; }
        public string antcham_os { get; set; }
        public string antcham_cells_os_tick { get; set; }
        public string antcham_cells_os { get; set; }
        public string antcham_flare_os_tick { get; set; }
        public string antcham_flare_os { get; set; }
        public string antcham_hyphema_os_tick { get; set; }
        public string antcham_hypopyon_os_tick { get; set; }
        public string antcham_emulsified_os_tick { get; set; }
        public string antcham_vitreous_os_tick { get; set; }
        public string antcham_os_others_tick { get; set; }
        public string antcham_os_others_specify { get; set; }
        public string antcham_depth_od { get; set; }
        public string antcham_depth_option_od { get; set; }
        public string antcham_depth_option_specify_od { get; set; }
        public string antcham_depth_os { get; set; }
        public string antcham_depth_option_os { get; set; }
        public string antcham_depth_option_specify_os { get; set; }
        public string iris_od { get; set; }
        public string iris_od_heterochromia_tick { get; set; }
        public string iris_od_altrophy_tick { get; set; }
        public string iris_od_nevus_tick { get; set; }
        public string iris_od_iridectomy_tick { get; set; }
        public string iris_od_iris_tick { get; set; }
        public string iris_od_aniridia_tick { get; set; }
        public string iris_od_bombae_tick { get; set; }
        public string iris_od_coloboma_tick { get; set; }
        public string iris_od_others_tick { get; set; }
        public string iris_od_others_specify { get; set; }
        public string iris_os { get; set; }
        public string iris_os_heterochromia_tick { get; set; }
        public string iris_os_altrophy_tick { get; set; }
        public string iris_os_nevus_tick { get; set; }
        public string iris_os_iridectomy_tick { get; set; }
        public string iris_os_iris_tick { get; set; }
        public string iris_os_aniridia_tick { get; set; }
        public string iris_os_bombae_tick { get; set; }
        public string iris_os_coloboma_tick { get; set; }
        public string iris_os_others_tick { get; set; }
        public string iris_os_others_specify { get; set; }
        public string pup_od { get; set; }
        public string pup_od_polycoria_tick { get; set; }
        public string pup_od_corectopia_tick { get; set; }
        public string pup_od_pupillary_tick { get; set; }
        public string pup_od_patent_tick { get; set; }
        public string pup_od_d_shaped_tick { get; set; }
        public string pup_od_others_tick { get; set; }
        public string pup_od_others_specify { get; set; }
        public string pup_os { get; set; }
        public string pup_os_polycoria_tick { get; set; }
        public string pup_os_corectopia_tick { get; set; }
        public string pup_os_pupillary_tick { get; set; }
        public string pup_os_patent_tick { get; set; }
        public string pup_os_d_shaped_tick { get; set; }
        public string pup_os_others_tick { get; set; }
        public string pup_os_others_specify { get; set; }
        public string pup_react_od { get; set; }
        public string pup_react_od_marcus_tick { get; set; }
        public string pup_react_od_sluggish_tick { get; set; }
        public string pup_react_od_hippus_tick { get; set; }
        public string pup_react_od_adie_tick { get; set; }
        public string pup_react_od_amaurotic_tick { get; set; }
        public string pup_react_od_others_tick { get; set; }
        public string pup_react_od_others_specify { get; set; }
        public string pup_react_os { get; set; }
        public string pup_react_os_marcus_tick { get; set; }
        public string pup_react_os_sluggish_tick { get; set; }
        public string pup_react_os_hippus_tick { get; set; }
        public string pup_react_os_adie_tick { get; set; }
        public string pup_react_os_amaurotic_tick { get; set; }
        public string pup_react_os_others_tick { get; set; }
        public string pup_react_os_others_specify { get; set; }
        public string uvea_od { get; set; }
        public string uvea_ant_synechia_od_tick { get; set; }
        public string uvea_post_synechia_od_tick { get; set; }
        public string uvea_chlo_coloboma_od_tick { get; set; }
        public string uvea_tb_nodule_od_tick { get; set; }
        public string uvea_chlor_scar_od_tick { get; set; }
        public string uvea_chlor_nevus_od_tick { get; set; }
        public string uvea_od_others_tick { get; set; }
        public string uvea_od_others_specify { get; set; }
        public string uvea_os { get; set; }
        public string uvea_ant_synechia_os_tick { get; set; }
        public string uvea_post_synechia_os_tick { get; set; }
        public string uvea_chlo_coloboma_os_tick { get; set; }
        public string uvea_tb_nodule_os_tick { get; set; }
        public string uvea_chlor_scar_os_tick { get; set; }
        public string uvea_chlor_nevus_os_tick { get; set; }
        public string uvea_os_others_tick { get; set; }
        public string uvea_os_others_specify { get; set; }
        public string phakic_od { get; set; }
        public string phakic_pseudo_od { get; set; }
        public string phakic_os { get; set; }
        public string phakic_pseudo_os { get; set; }
        public string capsule_od { get; set; }
        public string capsule_od_psuedoexfoliation_tick { get; set; }
        public string capsule_od_PCO_tick { get; set; }
        public string capsule_od_others_tick { get; set; }
        public string capsule_od_others_specify { get; set; }
        public string capsule_os { get; set; }
        public string capsule_os_psuedoexfoliation_tick { get; set; }
        public string capsule_os_PCO_tick { get; set; }
        public string capsule_os_others_tick { get; set; }
        public string capsule_os_others_specify { get; set; }
        public string phacodonesis_od_tick { get; set; }
        public string sublaxated_od_tick { get; set; }
        public string dislocated_od_tick { get; set; }
        public string none_od_tick { get; set; }
        public string phacodonesis_os_tick { get; set; }
        public string sublaxated_os_tick { get; set; }
        public string dislocated_os_tick { get; set; }
        public string none_os_tick { get; set; }
        public string ed_o1 { get; set; }
        public string ed_o2 { get; set; }
        public string ni_od { get; set; }
        public string ni_os { get; set; }
        public string ci_od { get; set; }
        public string ci_os { get; set; }
        public string p1_od { get; set; }
        public string p1_os { get; set; }
        public string mature_cataract_od { get; set; }
        public string mature_cataract_os { get; set; }
        public string complicated_cataract_od { get; set; }
        public string complicated_cataract_os { get; set; }
        public string special_test_od { get; set; }
        public string special_test_os { get; set; }
        public string tearfilm_od { get; set; }
        public string tearfilm_os { get; set; }
        public string tbut_od { get; set; }
        public string tbut_os { get; set; }
        public string syring_prob_od { get; set; }
        public string syring_prob_specify_od { get; set; }
        public string syring_prob_os { get; set; }
        public string syring_prob_specify_os { get; set; }
        public string tonometry_od { get; set; }
        public string tonometry_od_value { get; set; }
        public string tonometry_od_time { get; set; }
        public string tonometry_od_media_tick { get; set; }
        public string tonometry_od_cooperation_tick { get; set; }
        public string tonometry_od_fixation_tick { get; set; }
        public string tonometry_od_others_tick { get; set; }
        public string tonometry_od_others_specify { get; set; }
        public string tonometry_os { get; set; }
        public string tonometry_os_value { get; set; }
        public string tonometry_os_time { get; set; }
        public string tonometry_os_media_tick { get; set; }
        public string tonometry_os_cooperation_tick { get; set; }
        public string tonometry_os_fixation_tick { get; set; }
        public string tonometry_os_others_tick { get; set; }
        public string tonometry_os_others_specify { get; set; }
        public string gonioscopy_od { get; set; }
        public string gonioscopy_value_od { get; set; }
        public string gonioscopy_od_media_tick { get; set; }
        public string gonioscopy_od_cooperation_tick { get; set; }
        public string gonioscopy_od_fixation_tick { get; set; }
        public string gonioscopy_od_others_tick { get; set; }
        public string gonioscopy_od_others_specify { get; set; }
        public string gonioscopy_od_superior { get; set; }
        public string gonioscopy_od_inferior { get; set; }
        public string gonioscopy_od_nasal { get; set; }
        public string gonioscopy_od_temporal { get; set; }
        public string gonioscopy_od_other { get; set; }
        public string gonioscopy_od_other_specify { get; set; }
        public string gonioscopy_os { get; set; }
        public string gonioscopy_value_os { get; set; }
        public string gonioscopy_os_media_tick { get; set; }
        public string gonioscopy_os_cooperation_tick { get; set; }
        public string gonioscopy_os_fixation_tick { get; set; }
        public string gonioscopy_os_others_tick { get; set; }
        public string gonioscopy_os_others_specify { get; set; }
        public string gonioscopy_os_superior { get; set; }
        public string gonioscopy_os_inferior { get; set; }
        public string gonioscopy_os_nasal { get; set; }
        public string gonioscopy_os_temporal { get; set; }
        public string gonioscopy_os_other { get; set; }
        public string gonioscopy_os_other_specify { get; set; }
        public string ant_segment_remarks_od { get; set; }
        public string ant_segment_remarks_os { get; set; }
        public string post_segment { get; set; }
        public string vitreous_od { get; set; }
        public string vitreous_od_hemorrhage_tick { get; set; }
        public string vitreous_od_hylosis_tick { get; set; }
        public string vitreous_od_sinchysis_tick { get; set; }
        public string vitreous_od_degeneration_tick { get; set; }
        public string vitreous_od_proliferative_tick { get; set; }
        public string vitreous_od_vitreomacular_tick { get; set; }
        public string vitreous_od_no_view_tick { get; set; }
        public string vitreous_od_others_tick { get; set; }
        public string vitreous_od_others_specify { get; set; }
        public string vitreous_os { get; set; }
        public string vitreous_os_hemorrhage_tick { get; set; }
        public string vitreous_os_hylosis_tick { get; set; }
        public string vitreous_os_sinchysis_tick { get; set; }
        public string vitreous_os_degeneration_tick { get; set; }
        public string vitreous_os_proliferative_tick { get; set; }
        public string vitreous_os_vitreomacular_tick { get; set; }
        public string vitreous_os_no_view_tick { get; set; }
        public string vitreous_os_others_tick { get; set; }
        public string vitreous_os_others_specify { get; set; }
        public string disc_od { get; set; }
        public string disc_od_ldisk_tick { get; set; }
        public string disc_od_sdisk_tick { get; set; }
        public string disc_od_disk_drusion_tick { get; set; }
        public string disc_od_disk_pale_tick { get; set; }
        public string disc_od_peri_tick { get; set; }
        public string disc_od_optic_atrophy_tick { get; set; }
        public string disc_od_myopic_tick { get; set; }
        public string disc_od_staphy_tick { get; set; }
        public string disc_od_others_tick { get; set; }
        public string disc_od_others_specify { get; set; }
        public string disc_os { get; set; }
        public string disc_os_ldisk_tick { get; set; }
        public string disc_os_sdisk_tick { get; set; }
        public string disc_os_disk_drusion_tick { get; set; }
        public string disc_os_disk_pale_tick { get; set; }
        public string disc_os_peri_tick { get; set; }
        public string disc_os_optic_atrophy_tick { get; set; }
        public string disc_os_myopic_tick { get; set; }
        public string disc_os_staphy_tick { get; set; }
        public string disc_os_others_tick { get; set; }
        public string disc_os_others_specify { get; set; }
        public string cdr_od { get; set; }
        public string cdr_od_input { get; set; }
        public string cdr_v_od_input { get; set; }
        public string cdr_near_cupping_od_tick { get; set; }
        public string cdr_glau_suspect_od_tick { get; set; }
        public string cdr_glaucomatous_od_tick { get; set; }
        public string cdr_neuro_od_tick { get; set; }
        public string cdr_inferior_od_tick { get; set; }
        public string cdr_superior_od_tick { get; set; }
        public string cdr_nasal_od_tick { get; set; }
        public string cdr_temporal_od_tick { get; set; }
        public string cdr_os { get; set; }
        public string cdr_os_input { get; set; }
        public string cdr_v_os_input { get; set; }
        public string cdr_near_cupping_os_tick { get; set; }
        public string cdr_glau_suspect_os_tick { get; set; }
        public string cdr_glaucomatous_os_tick { get; set; }
        public string cdr_neuro_os_tick { get; set; }
        public string cdr_inferior_os_tick { get; set; }
        public string cdr_superior_os_tick { get; set; }
        public string cdr_nasal_os_tick { get; set; }
        public string cdr_temporal_os_tick { get; set; }
        public string avr_od { get; set; }
        public string avr_od_attenuated_tick { get; set; }
        public string avr_od_tortuous_tick { get; set; }
        public string avr_od_crvo_tick { get; set; }
        public string avr_od_crvo_superior_tick { get; set; }
        public string avr_od_crvo_inferior_tick { get; set; }
        public string avr_od_crvo_sup_temporal_tick { get; set; }
        public string avr_od_crvo_inf_temporal_tick { get; set; }
        public string avr_od_brvo_tick { get; set; }
        public string avr_od_brvo_superior_tick { get; set; }
        public string avr_od_brvo_inferior_tick { get; set; }
        public string avr_od_brvo_sup_temporal_tick { get; set; }
        public string avr_od_brvo_inf_temporal_tick { get; set; }
        public string avr_od_crao_tick { get; set; }
        public string avr_od_crao_superior_tick { get; set; }
        public string avr_od_crao_inferior_tick { get; set; }
        public string avr_od_crao_sup_temporal_tick { get; set; }
        public string avr_od_crao_inf_temporal_tick { get; set; }
        public string avr_od_brao_tick { get; set; }
        public string avr_od_brao_superior_tick { get; set; }
        public string avr_od_brao_inferior_tick { get; set; }
        public string avr_od_brao_sup_temporal_tick { get; set; }
        public string avr_od_brao_inf_temporal_tick { get; set; }
        public string avr_od_other_tick { get; set; }
        public string avr_od_other_specify { get; set; }
        public string avr_os { get; set; }
        public string avr_os_attenuated_tick { get; set; }
        public string avr_os_tortuous_tick { get; set; }
        public string avr_os_crvo_tick { get; set; }
        public string avr_os_crvo_superior_tick { get; set; }
        public string avr_os_crvo_inferior_tick { get; set; }
        public string avr_os_crvo_sup_temporal_tick { get; set; }
        public string avr_os_crvo_inf_temporal_tick { get; set; }
        public string avr_os_brvo_tick { get; set; }
        public string avr_os_brvo_superior_tick { get; set; }
        public string avr_os_brvo_inferior_tick { get; set; }
        public string avr_os_brvo_sup_temporal_tick { get; set; }
        public string avr_os_brvo_inf_temporal_tick { get; set; }
        public string avr_os_crao_tick { get; set; }
        public string avr_os_crao_superior_tick { get; set; }
        public string avr_os_crao_inferior_tick { get; set; }
        public string avr_os_crao_sup_temporal_tick { get; set; }
        public string avr_os_crao_inf_temporal_tick { get; set; }
        public string avr_os_brao_tick { get; set; }
        public string avr_os_brao_superior_tick { get; set; }
        public string avr_os_brao_inferior_tick { get; set; }
        public string avr_os_brao_sup_temporal_tick { get; set; }
        public string avr_os_brao_inf_temporal_tick { get; set; }
        public string avr_os_other_tick { get; set; }
        public string avr_os_other_specify { get; set; }
        public string macula_od { get; set; }
        public string macula_od_emm_tick { get; set; }
        public string macula_od_amd_tick { get; set; }
        public string macula_od_wet_amd_tick { get; set; }
        public string macula_od_dry_amd_tick { get; set; }
        public string macula_od_maculopathy_tick { get; set; }
        public string macula_od_others_tick { get; set; }
        public string macula_od_others_specify { get; set; }
        public string macula_os { get; set; }
        public string macula_os_emm_tick { get; set; }
        public string macula_os_amd_tick { get; set; }
        public string macula_os_wet_amd_tick { get; set; }
        public string macula_os_dry_amd_tick { get; set; }
        public string macula_os_maculopathy_tick { get; set; }
        public string macula_os_others_tick { get; set; }
        public string macula_os_others_specify { get; set; }
        public string fovea_od { get; set; }
        public string fovea_od_reflex_tick { get; set; }
        public string fovea_od_reflex_prescent_tick { get; set; }
        public string fovea_od_reflex_dull_tick { get; set; }
        public string fovea_od_reflex_others_tick { get; set; }
        public string fovea_od_reflex_others_specify { get; set; }
        public string fovea_os { get; set; }
        public string fovea_os_reflex_tick { get; set; }
        public string fovea_os_reflex_prescent_tick { get; set; }
        public string fovea_os_reflex_dull_tick { get; set; }
        public string fovea_os_reflex_others_tick { get; set; }
        public string fovea_os_reflex_others_specify { get; set; }
        public string retinal_find_od { get; set; }
        public string retinal_find_od_erm_tick { get; set; }
        public string retinal_find_od_hemi_tick { get; set; }
        public string retinal_find_od_dr_tick { get; set; }
        public string retinal_find_od_npdr_tick { get; set; }
        public string retinal_find_od_mild_npdr_tick { get; set; }
        public string retinal_find_od_mode_npdr_tick { get; set; }
        public string retinal_find_od_seve_npdr_tick { get; set; }
        public string retinal_find_od_vseve_npdr_tick { get; set; }
        public string retinal_find_od_csme_tick { get; set; }
        public string retinal_find_od_pdr_tick { get; set; }
        public string retinal_find_od_nvd_tick { get; set; }
        public string retinal_find_od_nve_tick { get; set; }
        public string retinal_find_od_htn_tick { get; set; }
        public string retinal_find_od_htn_i_tick { get; set; }
        public string retinal_find_od_htn_ii_tick { get; set; }
        public string retinal_find_od_htn_iii_tick { get; set; }
        public string retinal_find_od_htn_iv_tick { get; set; }
        public string retinal_find_od_rp_tick { get; set; }
        public string retinal_find_od_other_tick { get; set; }
        public string retinal_find_od_other_specify { get; set; }
        public string retinal_find_os { get; set; }
        public string retinal_find_os_erm_tick { get; set; }
        public string retinal_find_os_hemi_tick { get; set; }
        public string retinal_find_os_dr_tick { get; set; }
        public string retinal_find_os_npdr_tick { get; set; }
        public string retinal_find_os_mild_npdr_tick { get; set; }
        public string retinal_find_os_mode_npdr_tick { get; set; }
        public string retinal_find_os_seve_npdr_tick { get; set; }
        public string retinal_find_os_vseve_npdr_tick { get; set; }
        public string retinal_find_os_csme_tick { get; set; }
        public string retinal_find_os_pdr_tick { get; set; }
        public string retinal_find_os_nvd_tick { get; set; }
        public string retinal_find_os_nve_tick { get; set; }
        public string retinal_find_os_htn_tick { get; set; }
        public string retinal_find_os_htn_i_tick { get; set; }
        public string retinal_find_os_htn_ii_tick { get; set; }
        public string retinal_find_os_htn_iii_tick { get; set; }
        public string retinal_find_os_htn_iv_tick { get; set; }
        public string retinal_find_os_rp_tick { get; set; }
        public string retinal_find_os_other_tick { get; set; }
        public string retinal_find_os_other_specify { get; set; }
        public string post_seg_remarks_od { get; set; }
        public string post_seg_remarks_os { get; set; }
        public string diag_cataract_od_tick { get; set; }
        public string diag_cataract_option_od { get; set; }
        public string diag_cataract_loc_nuclear_od_tick { get; set; }
        public string diag_cataract_loc_nuclear_od { get; set; }
        public string diag_cataract_loc_cortical_od_tick { get; set; }
        public string diag_cataract_loc_cortical_od { get; set; }
        public string diag_cataract_loc_posterior_od_tick { get; set; }
        public string diag_cataract_loc_posterior_od { get; set; }
        public string diag_cataract_others_od_specify { get; set; }
        public string diag_galucoma_od_tick { get; set; }
        public string diag_galucoma_suspect_od { get; set; }
        public string diag_galucoma_suspect_od_specify { get; set; }
        public string diag_corneal_od_tick { get; set; }
        public string diag_corneal_od_specify { get; set; }
        public string diag_age_od_tick { get; set; }
        public string diag_age_od { get; set; }
        public string diag_diabetic_od_tick { get; set; }
        public string diag_diabetic_poli_od { get; set; }
        public string diag_diabetic_poli_od_mild_tick { get; set; }
        public string diag_diabetic_poli_od_mod_tick { get; set; }
        public string diag_diabetic_poli_od_sev_tick { get; set; }
        public string diag_diabetic_poli_od_vsev_tick { get; set; }
        public string diag_diabetic_poli_od_csme_tick { get; set; }
        public string diag_diabetic_poli_nvd_od_tick { get; set; }
        public string diag_diabetic_poli_nve_od_tick { get; set; }
        public string diag_refractive_od_tick { get; set; }
        public string diag_refractive_myopia_od_tick { get; set; }
        public string diag_refractive_hypmetro_od_tick { get; set; }
        public string diag_refractive_astig_od_tick { get; set; }
        public string diag_refractive_astig_od_specify { get; set; }
        public string diag_refractive_pres_od_tick { get; set; }
        public string diag_ocular_od_tick { get; set; }
        public string diag_ocular_od { get; set; }
        public string diag_others_od_tick { get; set; }
        public string diag_oculoplasty_od_tick { get; set; }
        public string diag_oculoplasty_od_specify { get; set; }
        public string diag_neuro_od_tick { get; set; }
        public string diag_neuro_od_specify { get; set; }
        public string diag_retinal_od_tick { get; set; }
        public string diag_retinal_od_specify { get; set; }
        public string diag_retinal_epi_od_tick { get; set; }
        public string diag_retinal_epi_od_specify { get; set; }
        public string diag_retinal_hemi_od_tick { get; set; }
        public string diag_retinal_hemi_od_specify { get; set; }
        public string diag_retinal_htn_od_tick { get; set; }
        public string diag_retinal_htn_od { get; set; }
        public string diag_others_rp_od_tick { get; set; }
        public string diag_retinal_others_od_tick { get; set; }
        public string diag_retinal_others_od_specify { get; set; }
        public string diag_extra_ocular_od_tick { get; set; }
        public string diag_extra_ocular_od_specify { get; set; }
        public string diag_squint_od_tick { get; set; }
        public string diag_squint_od_specify { get; set; }
        public string diag_uvea_od_tick { get; set; }
        public string diag_uvea_od_specify { get; set; }
        public string diag_globe_od_tick { get; set; }
        public string diag_globe_od_specify { get; set; }
        public string diag_pseudo_od_tick { get; set; }
        public string diag_pseudo_od_specify { get; set; }
        public string diag_cataract_surg_od_tick { get; set; }
        public string diag_cataract_surg_od_specify { get; set; }
        public string diag_other_dis_others_od_tick { get; set; }
        public string diag_other_dis_others_od_specify { get; set; }
        public string diag_no_abnormality_od_tick { get; set; }
        public string diag_remarks_od_specify { get; set; }
        public string diag_cataract_os_tick { get; set; }
        public string diag_cataract_option_os { get; set; }
        public string diag_cataract_loc_nuclear_os_tick { get; set; }
        public string diag_cataract_loc_nuclear_os { get; set; }
        public string diag_cataract_loc_cortical_os_tick { get; set; }
        public string diag_cataract_loc_cortical_os { get; set; }
        public string diag_cataract_loc_posterior_os_tick { get; set; }
        public string diag_cataract_loc_posterior_os { get; set; }
        public string diag_cataract_others_os_specify { get; set; }
        public string diag_galucoma_os_tick { get; set; }
        public string diag_galucoma_suspect_os { get; set; }
        public string diag_galucoma_suspect_os_specify { get; set; }
        public string diag_corneal_os_tick { get; set; }
        public string diag_corneal_os_specify { get; set; }
        public string diag_age_os_tick { get; set; }
        public string diag_age_os { get; set; }
        public string diag_diabetic_os_tick { get; set; }
        public string diag_diabetic_poli_os { get; set; }
        public string diag_diabetic_poli_os_mild_tick { get; set; }
        public string diag_diabetic_poli_os_mod_tick { get; set; }
        public string diag_diabetic_poli_os_sev_tick { get; set; }
        public string diag_diabetic_poli_os_vsev_tick { get; set; }
        public string diag_diabetic_poli_os_csme_tick { get; set; }
        public string diag_diabetic_poli_nvd_os_tick { get; set; }
        public string diag_diabetic_poli_nve_os_tick { get; set; }
        public string diag_refractive_os_tick { get; set; }
        public string diag_refractive_myopia_os_tick { get; set; }
        public string diag_refractive_hypmetro_os_tick { get; set; }
        public string diag_refractive_astig_os_tick { get; set; }
        public string diag_refractive_astig_os_specify { get; set; }
        public string diag_refractive_pres_os_tick { get; set; }
        public string diag_ocular_os_tick { get; set; }
        public string diag_ocular_os { get; set; }
        public string diag_others_os_tick { get; set; }
        public string diag_oculoplasty_os_tick { get; set; }
        public string diag_oculoplasty_os_specify { get; set; }
        public string diag_neuro_os_tick { get; set; }
        public string diag_neuro_os_specify { get; set; }
        public string diag_retinal_os_tick { get; set; }
        public string diag_retinal_os_specify { get; set; }
        public string diag_retinal_epi_os_tick { get; set; }
        public string diag_retinal_epi_os_specify { get; set; }
        public string diag_retinal_hemi_os_tick { get; set; }
        public string diag_retinal_hemi_os_specify { get; set; }
        public string diag_retinal_htn_os_tick { get; set; }
        public string diag_retinal_htn_os { get; set; }
        public string diag_others_rp_os_tick { get; set; }
        public string diag_retinal_others_os_tick { get; set; }
        public string diag_retinal_others_os_specify { get; set; }
        public string diag_extra_ocular_os_tick { get; set; }
        public string diag_extra_ocular_os_specify { get; set; }
        public string diag_squint_os_tick { get; set; }
        public string diag_squint_os_specify { get; set; }
        public string diag_uvea_os_tick { get; set; }
        public string diag_uvea_os_specify { get; set; }
        public string diag_globe_os_tick { get; set; }
        public string diag_globe_os_specify { get; set; }
        public string diag_pseudo_os_tick { get; set; }
        public string diag_pseudo_os_specify { get; set; }
        public string diag_cataract_surg_os_tick { get; set; }
        public string diag_cataract_surg_os_specify { get; set; }
        public string diag_other_dis_others_os_tick { get; set; }
        public string diag_other_dis_others_os_specify { get; set; }
        public string diag_no_abnormality_os_tick { get; set; }
        public string diag_remarks_os_specify { get; set; }
        public string cause_impairment_od { get; set; }
        public string cause_impairment_specify_od { get; set; }
        public string cause_impairment_os { get; set; }
        public string cause_impairment_specify_os { get; set; }
        public string psi_treatment_od { get; set; }
        public string medical_treatment_od_tick { get; set; }
        public string surgrical_treatment_od_tick { get; set; }
        public string surgrical_treatment_od_specify { get; set; }
        public string surgrical_treatment_os_specify { get; set; }
        public string laser_treatment_od_tick { get; set; }
        public string laser_treatment_od_specify { get; set; }
        public string laser_treatment_os_specify { get; set; }
        public string spectacle_treatment_od_tick { get; set; }
        public string spectacle_treatment_presbyopic_od_tick { get; set; }
        public string spectacle_treatment_distance_od_tick { get; set; }
        public string spectacle_treatment_biofocal_od_tick { get; set; }
        public string spectacle_treatment_multifocal_od_tick { get; set; }
        public string sub_referer_od_tick { get; set; }
        public string sub_referer_cornea_od_tick { get; set; }
        public string sub_referer_retina_od_tick { get; set; }
        public string sub_referer_glaucoma_od_tick { get; set; }
        public string sub_referer_opal_od_tick { get; set; }
        public string sub_referer_ref_error_od_tick { get; set; }
        public string sub_referer_squint_od_tick { get; set; }
        public string sub_referer_uvea_od_tick { get; set; }
        public string sub_referer_neuro_od_tick { get; set; }
        public string psi_treatment_os { get; set; }
        public string spectacle_treatment_os_tick { get; set; }
        public string spectacle_treatment_presbyopic_os_tick { get; set; }
        public string spectacle_treatment_distance_os_tick { get; set; }
        public string spectacle_treatment_biofocal_os_tick { get; set; }
        public string spectacle_treatment_multifocal_os_tick { get; set; }
        public string sub_referer_os_tick { get; set; }
        public string sub_referer_cornea_os_tick { get; set; }
        public string sub_referer_retina_os_tick { get; set; }
        public string sub_referer_glaucoma_os_tick { get; set; }
        public string sub_referer_opal_os_tick { get; set; }
        public string sub_referer_ref_error_os_tick { get; set; }
        public string sub_referer_squint_os_tick { get; set; }
        public string sub_referer_uvea_os_tick { get; set; }
        public string sub_referer_neuro_os_tick { get; set; }
        public string follow_up { get; set; }
        public string intervention_plan { get; set; }


    }
}