using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace medipro.api.Medipro.Models.NewModels.EyeDocs.PivotTitle
{
    public class PastEyeHistoryPivot_dt
    {
        public DateTime ddate { get; set; }
        public string mrdno { get; set; }
        public int clusterno { get; set; }  
        public int kesid { get; set; }
        public string pastprob_od { get; set; }
        public string pastprob_os { get; set; }
        public string glaucoma_od_tick { get; set; }
        public string glaucoma_od_time { get; set; }
        public string glaucoma_os_tick { get; set; }
        public string glaucoma_os_time { get; set; }
        public string cataract_od_tick { get; set; }
        public string cataract_od_time { get; set; }
        public string cataract_os_tick { get; set; }
        public string cataract_os_time { get; set; }
        public string retina_od_tick { get; set; }
        public string retina_od_time { get; set; }
        public string retina_od_type { get; set; }
        public string retina_os_tick { get; set; }
        public string retina_os_time { get; set; }
        public string squint_od_tick { get; set; }
        public string squint_od_time { get; set; }
        public string squint_os_tick { get; set; }
        public string squint_os_time { get; set; }
        public string corneal_od_tick { get; set; }
        public string corneal_od_time { get; set; }
        public string corneal_os_tick { get; set; }
        public string corneal_os_time { get; set; }
        public string opal_od_tick { get; set; }
        public string opal_od_time { get; set; }
        public string opal_os_tick { get; set; }
        public string opal_os_time { get; set; }
        public string opal_os_type { get; set; }
        public string uveal_od_tick { get; set; }
        public string uveal_od_time { get; set; }
        public string uveal_os_tick { get; set; }
        public string uveal_os_time { get; set; }
        public string ophthalmic_od_tick { get; set; }
        public string ophthalmic_od_time { get; set; }
        public string ophthalmic_os_tick { get; set; }
        public string ophthalmic_os_time { get; set; }
        public string ophthalmic_os_type { get; set; }
        public string otherpastprob_od_tick { get; set; }
        public string otherpastprob_od_time { get; set; }
        public string otherpastprob_od_specify { get; set; }
        public string otherpastprob_os_tick { get; set; }
        public string otherpastprob_os_time { get; set; }
        public string otherpastprob_os_specify { get; set; }
        public string pastprob_remarks_od { get; set; }
        public string pastprob_remarks_os { get; set; }
        public string ocu_trauma_od { get; set; }
        public string ocu_trauma_blunt_od { get; set; }
        public string ocu_trauma_penetrating_od { get; set; }
        public string ocu_trauma_others_od { get; set; }
        public string ocu_trauma_others_specify_od { get; set; }
        public string ocu_trauma_os { get; set; }
        public string ocu_trauma_blunt_os { get; set; }
        public string ocu_trauma_penetrating_os { get; set; }
        public string ocu_trauma_others_os { get; set; }
        public string ocu_trauma_others_specify_os { get; set; }
        public string ocu_trauma_blunt_od_time { get; set; }
        public string ocu_trauma_blunt_medi_od_tick { get; set; }
        public string ocu_trauma_blunt_surg_od_tick { get; set; }
        public string ocu_trauma_blunt_dk_od_tick { get; set; }
        public string ocu_trauma_blunt_visual_loss_od { get; set; }
        public string ocu_trauma_blunt_os_time { get; set; }
        public string ocu_trauma_blunt_medi_os_tick { get; set; }
        public string ocu_trauma_blunt_surg_os_tick { get; set; }
        public string ocu_trauma_blunt_dk_os_tick { get; set; }
        public string ocu_trauma_blunt_visual_loss_os { get; set; }
        public string ocu_trauma_pent_od_time { get; set; }
        public string ocu_trauma_pent_medi_od_tick { get; set; }
        public string ocu_trauma_pent_surg_od_tick { get; set; }
        public string ocu_trauma_pent_dk_od_tick { get; set; }
        public string ocu_trauma_pent_visual_loss_od { get; set; }
        public string ocu_trauma_pent_os_time { get; set; }
        public string ocu_trauma_pent_medi_os_tick { get; set; }
        public string ocu_trauma_pent_surg_os_tick { get; set; }
        public string ocu_trauma_pent_dk_os_tick { get; set; }
        public string ocu_trauma_pent_visual_loss_os { get; set; }
        public string ocu_trauma_other_specify { get; set; }
        public string ocu_trauma_other_od_time { get; set; }
        public string ocu_trauma_other_medi_od_tick { get; set; }
        public string ocu_trauma_other_surg_od_tick { get; set; }
        public string ocu_trauma_other_dk_od_tick { get; set; }
        public string ocu_trauma_other_visual_loss_od { get; set; }
        public string ocu_trauma_other_os_time { get; set; }
        public string ocu_trauma_other_medi_os_tick { get; set; }
        public string ocu_trauma_other_surg_os_tick { get; set; }
        public string ocu_trauma_other_dk_os_tick { get; set; }
        public string ocu_trauma_other_visual_loss_os { get; set; }
        public string surglaser_od { get; set; }
        public string surglaser_os { get; set; }
        public string glaucoma_surg_od_tick { get; set; }
        public string glaucoma_surg_od_name { get; set; }
        public string glaucoma_surg_od_number { get; set; }
        public string glaucoma_surg_od_time { get; set; }
        public string glaucoma_surg_os_tick { get; set; }
        public string glaucoma_surg_os_name { get; set; }
        public string glaucoma_surg_os_number { get; set; }
        public string glaucoma_surg_os_time { get; set; }
        public string cataract_surg_od_tick { get; set; }
        public string cataract_surg_od_name { get; set; }
        public string cataract_surg_od_number { get; set; }
        public string cataract_surg_od_time { get; set; }
        public string cataract_surg_os_tick { get; set; }
        public string cataract_surg_os_name { get; set; }
        public string cataract_surg_os_number { get; set; }
        public string cataract_surg_os_time { get; set; }
        public string retina_surg_od_tick { get; set; }
        public string retina_surg_od_name { get; set; }
        public string retina_surg_od_number { get; set; }
        public string retina_surg_od_time { get; set; }
        public string retina_surg_os_tick { get; set; }
        public string retina_surg_os_name { get; set; }
        public string retina_surg_os_number { get; set; }
        public string retina_surg_os_time { get; set; }
        public string squint_surg_od_tick { get; set; }
        public string squint_surg_od_name { get; set; }
        public string squint_surg_od_number { get; set; }
        public string squint_surg_od_time { get; set; }
        public string squint_surg_os_tick { get; set; }
        public string squint_surg_os_name { get; set; }
        public string squint_surg_os_number { get; set; }
        public string squint_surg_os_time { get; set; }
        public string corneal_surg_od_tick { get; set; }
        public string corneal_surg_od_name { get; set; }
        public string corneal_surg_od_number { get; set; }
        public string corneal_surg_od_time { get; set; }
        public string corneal_surg_os_tick { get; set; }
        public string corneal_surg_os_name { get; set; }
        public string corneal_surg_os_number { get; set; }
        public string corneal_surg_os_time { get; set; }
        public string related_surg_od_tick { get; set; }
        public string related_surg_od_name { get; set; }
        public string related_surg_od_number { get; set; }
        public string related_surg_od_time { get; set; }
        public string related_surg_os_tick { get; set; }
        public string related_surg_os_name { get; set; }
        public string related_surg_os_number { get; set; }
        public string related_surg_os_time { get; set; }
        public string uveal_surg_od_tick { get; set; }
        public string uveal_surg_od_name { get; set; }
        public string uveal_surg_od_number { get; set; }
        public string uveal_surg_od_time { get; set; }
        public string uveal_surg_os_tick { get; set; }
        public string uveal_surg_os_name { get; set; }
        public string uveal_surg_os_number { get; set; }
        public string uveal_surg_os_time { get; set; }
        public string ophthalmic_surg_od_tick { get; set; }
        public string ophthalmic_surg_od_name { get; set; }
        public string ophthalmic_surg_od_number { get; set; }
        public string ophthalmic_surg_od_time { get; set; }
        public string ophthalmic_surg_os_tick { get; set; }
        public string ophthalmic_surg_os_name { get; set; }
        public string ophthalmic_surg_os_number { get; set; }
        public string ophthalmic_surg_os_time { get; set; }
        public string others_surg_od_tick { get; set; }
        public string others_surg_od_name { get; set; }
        public string others_surg_od_number { get; set; }
        public string others_surg_od_time { get; set; }
        public string others_surg_od_specify { get; set; }
        public string others_surg_os_tick { get; set; }
        public string others_surg_os_name { get; set; }
        public string others_surg_os_number { get; set; }
        public string others_surg_os_time { get; set; }
        public string others_surg_os_specify { get; set; }
        public string surg_remarks_od { get; set; }
        public string surg_remarks_os { get; set; }
        public string systematicillness { get; set; }
        public string hypertension_od_tick { get; set; }
        public string hypertension_od_time { get; set; }
        public string hypertension_od_medicine { get; set; }
        public string diabetic_od_tick { get; set; }
        public string diabetes_type { get; set; }
        public string diabetic_od_time { get; set; }
        public string diabetic_od_medicine { get; set; }
        public string asthma_od_tick { get; set; }
        public string asthma_od_time { get; set; }
        public string asthma_od_medicine { get; set; }
        public string cardiac_od_tick { get; set; }
        public string cardiac_od_time { get; set; }
        public string cardiac_od_medicine { get; set; }
        public string thyroid_od_tick { get; set; }
        public string thyroid_od_time { get; set; }
        public string thyroid_od_medicine { get; set; }
        public string accident_od_tick { get; set; }
        public string accident_od_time { get; set; }
        public string accident_od_medicine { get; set; }
        public string hiv_tick { get; set; }
        public string hiv_time { get; set; }
        public string hiv_medicine { get; set; }
        public string syphillis_tick { get; set; }
        public string syphillis_time { get; set; }
        public string syphillis_medicine { get; set; }
        public string hyperlipidemia_od_tick { get; set; }
        public string hyperlipidemia_od_time { get; set; }
        public string hyperlipidemia_od_medicine { get; set; }
        public string kiddiseases_od_tick { get; set; }
        public string kiddiseases_od_time { get; set; }
        public string kiddiseases_od_medicine { get; set; }
        public string anemia_od_tick { get; set; }
        public string anemia_od_time { get; set; }
        public string anemia_od_medicine { get; set; }
        public string eyeprobpregnancy_od_tick { get; set; }
        public string eyeprobpregnancy_od_time { get; set; }
        public string eyeprobpregnancy_od_medicine { get; set; }
        public string rheumatological_od_tick { get; set; }
        public string rheumatological_od_time { get; set; }
        public string rheumatological_od_medicine { get; set; }
        public string infectiousdisease_od_tick { get; set; }
        public string infectiousdisease_od_time { get; set; }
        public string infectiousdisease_od_medicine { get; set; }
        public string tubercolosis_tick { get; set; }
        public string tubercolosis_time { get; set; }
        public string tubercolosis_medicine { get; set; }
        public string others_illness_od_tick { get; set; }
        public string others_illness_od_time { get; set; }
        public string others_illness_od_medicine { get; set; }
        public string others_illness_od_disease { get; set; }
        public string sys_illness_remarks { get; set; }
        public string sterioduse { get; set; }
        public string oral_od_tick { get; set; }
        public string oral_od_time { get; set; }
        public string oral_od_medication { get; set; }
        public string inj_sys_od_tick { get; set; }
        public string inj_sys_od_time { get; set; }
        public string inj_sys_od_medication { get; set; }
        public string inj_peri_od_tick { get; set; }
        public string inj_peri_od_time { get; set; }
        public string inj_peri_od_medication { get; set; }
        public string inhaler_od_tick { get; set; }
        public string inhaler_od_time { get; set; }
        public string inhaler_od_medication { get; set; }
        public string eye_drop_od_tick { get; set; }
        public string eye_drop_od_time { get; set; }
        public string eye_drop_od_medication { get; set; }
        public string skin_cream_od_tick { get; set; }
        public string skin_cream_od_time { get; set; }
        public string skin_cream_od_medication { get; set; }
        public string steroid_others_od_tick { get; set; }
        public string steroid_others_od_time { get; set; }
        public string steroid_others_od_medication { get; set; }
        public string steroid_others_od_specify { get; set; }
        public string fam_his_od { get; set; }
        public string fam_his_glaucoma_tick { get; set; }
        public string fam_his_cataract_tick { get; set; }
        public string fam_his_retina_tick { get; set; }
        public string fam_his_squint_tick { get; set; }
        public string fam_his_other_tick { get; set; }
        public string fam_his_others_specify { get; set; }
        public string fam_his_corneal_tick { get; set; }
        public string fam_his_opal_tick { get; set; }
        public string fam_his_uveal_tick { get; set; }
        public string fam_his_neuro_tick { get; set; }





    }
}