using medipro.api.Medipro.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;

namespace medipro.api.Medipro.Models.NewModels.ReportSectionModifyStructure
{
    public class SalesRegisterModify
    {
        public void SalesRegDatewise()
        {
            StringBuilder s = new StringBuilder();

            s.Append(" create procedure sp_SalesRegistrationbyDate ");
            s.Append(" (@init datetime,@final datetime,@firm int,@ipdsave int,@ipd int,@val int,@refid int,@initbilltime varchar(15), ");
            s.Append(" @finalbilltime varchar(15), @er int, @discount int,@canceled int,@insurance int,@salesbill int,@returnbill int,@paymode int,@billmode int, ");
            s.Append(" @morbidity int,@search varchar(50) , @userid int) ");
            s.Append(" as ");
            s.Append(" begin ");
            s.Append(" begin try ");
            s.Append(" begin transaction ");
            s.Append(" IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES ");
            s.Append(" WHERE TABLE_NAME = 'topdrecReport') ");
            s.Append(" DROP TABLE topdrecReport ");
            s.Append(" IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES ");
            s.Append(" WHERE TABLE_NAME = 'topdbillReport') ");
            s.Append(" DROP TABLE topdbillReport ");
            s.Append(" create table topdrecReport( ");
            s.Append(" inv_no varchar(11), amt float, disc_amt numeric(12,2), ");
            s.Append(" taxable numeric(12,2), nontaxable numeric(12,2), ");
            s.Append(" net numeric(12,2), reportuserid int ");
            s.Append(" ) ");
            s.Append(" create table topdbillReport( ");
            s.Append(" note1 varchar(30),note2 varchar(30),refid int , username varchar(50), insurance bit, canceled bit, note varchar(10), hospid int, ");
            s.Append(" bs_date varchar(10), ddate datetime, inv_no varchar(11), pname varchar(50), [address] varchar(250), ");
            s.Append(" telephone varchar(50),sex varchar(10), age int, amount float, discount float, vat float, roundoff numeric(12,2), net float, ipd bit, reg bit, ");
            s.Append(" icdcode varchar(1), referer varchar(50), appby varchar(30), reqby varchar(30), telno varchar(30), ");
            s.Append(" consultant varchar(50), taxable float, nontaxable float, patient_type varchar(20), branch_center varchar(20), reportuserid int ");
            s.Append(" ) ");
            s.Append(" if @ipdsave=0 ");
            s.Append(" begin ");
            s.Append(" if @morbidity=1 ");
            s.Append(" begin ");
            s.Append(" declare @value varchar(50) ");
            s.Append(" select @value = value from config where item='CONS_GROUP' ");
            s.Append(" select inv_no, sum(qty*rate) as amt, sum(disc_amt) as disc_amt, ");
            s.Append(" sum(case when vatamt<>0 then (qty*rate)-disc_amt else 0 end) as taxable, ");
            s.Append(" sum(case when vatamt<>0 then 0 else (qty*rate)-disc_amt end) as nontaxable, ");
            s.Append(" sum(vatamt) as vatamt, sum( (qty*rate)-disc_amt+vatamt ) as net ");
            s.Append(" into #tOpdrec ");
            s.Append(" From opdrec where ddate>=@init and ddate<=@final and firm= case when @firm=0 then firm else @firm end ");
            s.Append(" group by inv_no ");
            s.Append(" delete from topdrecReport where reportuserid=@userid ");
            s.Append(" insert into topdrecReport(inv_no , amt , disc_amt ,taxable , nontaxable ,net , reportuserid) ");
            s.Append(" select inv_no , amt , disc_amt ,taxable , nontaxable ,net , @userid from #topdrec ");
            s.Append(" select a.note1, a.note2, (case when @val=1 then a.refid ");
            s.Append(" when @val=0 then a.consid end) as refid , ");
            s.Append(" h.username, a.insurance, a.canceled, a.note, a.hospid, c.bs_Date, a.ddate, a.inv_no, ");
            s.Append(" b.pname, b.address, b.telephone, b.sex, cast( a.ageday/365 as int) as age, a.amount, a.discount+isnull(sum(d.discount),0) as discount , ");
            s.Append(" a.vat, -isnull(a.roundoff,0) as roundoff, a.amount-a.discount+a.vat-isnull(sum(d.discount),0)-isnull(a.roundoff,0) as Net, ipd, a.reg, ");
            s.Append(" isnull( (select 'Y' from opd_morbidity with (nolock) where a.inv_no=inv_no group by inv_no ),' ' ) as IcdCode, e.referer, a.appby, a.reqby, a.telno, f.referer as consultant, ");
            s.Append(" g.taxable, g.nontaxable, a.patient_type, a.branch_center ");
            s.Append(" into #tOpdbill ");
            s.Append(" from opdbill a with (nolock) left join member b with (nolock) on a.hospid=b.hospid left join calendar c with (nolock) on a.ddate=c.ad_date ");
            s.Append(" left join (select inv_no, sum(discount) as discount from invoicediscount group by inv_no ) d on a.inv_no=d.inv_no left join referer e with (nolock) on a.refid=e.refid ");
            s.Append(" left join referer f with (nolock) on a.consid=f.refid ");
            s.Append(" left join (select * From #topdrec ) g on a.inv_no=g.inv_no ");
            s.Append(" left join userlist h on a.[user]=h.userid ");
            s.Append(" where ");
            s.Append(" a.ddate>=@init and a.ddate<=@final ");
            s.Append(" and (a.ddate + (a.billtime)>=case when @initbilltime='0' then a.ddate+a.billtime else @init + @initbilltime end ");
            s.Append(" and a.ddate+(a.billtime)<=case when @finalbilltime='0' then a.ddate + a.billtime else @final + @finalbilltime end) ");
            s.Append(" and a.firm= case when @firm=0 then a.firm else @firm end  ");
            s.Append(" and a.ipd = case when @ipd = 2 then a.ipd else @ipd end ");
            s.Append(" and ( b.pname like '%'+@search+'%' or a.hospid like '%'+@search+'%') ");
            s.Append(" and ISNULL(case when @val=1 then a.refid when @val=0 then a.consid end,0) =case when @refid=0 ");
            s.Append(" then ISNULL(case when @val=1 then a.refid when @val=0 then a.consid end,0) else @refid end ");
            s.Append(" and a.er = case when @er=0 then a.er else @er end ");
            s.Append(" and a.discount=case when @discount=1 and a.DISCOUNT<>0 then a.discount ");
            s.Append(" when @discount=0 then a.discount end ");
            s.Append(" and a.AMOUNT= case when @salesbill=1 and a.amount>0 then a.amount ");
            s.Append(" when @salesbill= 0 then a.AMOUNT end ");
            s.Append(" and a.AMOUNT= case when @returnbill=1 and a.amount<0 then a.amount ");
            s.Append(" when @returnbill= 0 then a.AMOUNT end ");
            s.Append(" and isnull(a.[canceled],0) = case when @canceled=0 then isnull(a.[canceled],0) else @canceled end ");
            s.Append(" and a.insurance = case when @insurance = 0 then a.insurance else @insurance end ");
            s.Append(" and a.[user] = case when 0=0 then a.[user] else 0 end ");
            s.Append(" and a.p_type=case when @paymode=0 then a.p_type ");
            s.Append(" when @paymode=1 and a.p_type='cash' then a.p_type ");
            s.Append(" when @paymode=2 and a.p_type='credit' then a.p_type ");
            s.Append(" when @paymode=3 and a.p_type='card' then a.p_type end ");
            s.Append(" and a.billmode=case when @billmode=0 then a.billmode ");
            s.Append(" when @billmode=1 and a.billmode='general' then a.billmode ");
            s.Append(" when @billmode=2 and a.billmode='member' then a.billmode end ");
            s.Append(" and a.inv_no in (select e.inv_no from opdrec e with (nolock) left join service f with (nolock) on e.servid=f.servid ");
            s.Append(" where E.ddate>=@init and E.ddate<=@final and f.grpid=@value ) ");
            s.Append(" group by (case when @val=1 then a.refid ");
            s.Append(" when @val=0 then a.consid end) , ");
            s.Append(" a.insurance, a.canceled, a.note, a.hospid, c.bs_Date, a.ddate, a.inv_no, b.pname, b.address, b.telephone, a.amount, a.discount, ");
            s.Append(" a.vat, a.roundoff , ipd, a.reg, e.referer, a.appby, a.reqby, a.telno, f.referer, g.taxable, g.nontaxable, b.sex, cast( a.ageday/365 as int) , H.USERNAME , ");
            s.Append(" a.note1, a.note2, A.PATIENT_TYPE, a.branch_center ");
            s.Append(" order by a.ddate, a.inv_no ");
            s.Append(" delete from topdbillReport where reportuserid=@userid ");
            s.Append(" insert into topdbillReport (note1 ,note2 ,refid , username, insurance, canceled, note , hospid , bs_date , ddate , inv_no , pname , [address] , ");
            s.Append(" telephone ,sex , age, amount , discount , vat , roundoff , net , ipd , reg , icdcode , referer , appby , reqby , telno , consultant , ");
            s.Append(" taxable , nontaxable , patient_type, branch_center , reportuserid ) ");
            s.Append(" select note1 ,note2 ,refid , username, insurance, canceled, note , hospid , bs_date , ddate , inv_no , pname , [address] , ");
            s.Append(" telephone ,sex , age, amount , discount , vat , roundoff , net , ipd , reg , icdcode , referer , appby , reqby , telno , consultant , ");
            s.Append(" taxable , nontaxable , patient_type, branch_center , @userid from #tOpdbill ");
            s.Append(" select *, case when discount>0 then (discount/amount)* 100 else 0 end as disc_pc from topdbillReport ");
            s.Append(" where ");
            s.Append(" (pname like '%'+@search+'%' or inv_no like '%%' or hospid like '%'+@search+'%' ) ");
            s.Append(" end ");
            s.Append(" else ");
            s.Append(" begin ");
            s.Append(" select inv_no, sum(qty*rate) as amt, sum(disc_amt) as disc_amt, ");
            s.Append(" sum(case when vatamt<>0 then (qty*rate)-disc_amt else 0 end) as taxable, ");
            s.Append(" sum(case when vatamt<>0 then 0 else (qty*rate)-disc_amt end) as nontaxable, ");
            s.Append(" sum(vatamt) as vatamt, sum( (qty*rate)-disc_amt+vatamt ) as net ");
            s.Append(" into #topdrec1 ");
            s.Append(" From opdrec where ddate>=@init and ddate<=@final and firm= case when @firm=0 then firm else @firm end ");
            s.Append(" group by inv_no ");
            s.Append(" delete from topdrecReport where reportuserid=@userid ");
            s.Append(" insert into topdrecReport(inv_no , amt , disc_amt ,taxable , nontaxable ,net , reportuserid) ");
            s.Append(" select inv_no , amt , disc_amt ,taxable , nontaxable ,net , @userid from #topdrec1 ");
            s.Append(" select a.note1, a.note2,(case when @val=1 then a.refid ");
            s.Append(" when @val=0 then a.consid end) as refid , ");
            s.Append(" h.username, a.insurance, a.canceled, a.note, a.hospid, c.bs_Date, a.ddate, a.inv_no, ");
            s.Append(" b.pname, b.address, b.telephone, b.sex, cast( a.ageday/365 as int) as age, a.amount, a.discount+isnull(sum(d.discount),0) as discount , ");
            s.Append(" a.vat, -isnull(a.roundoff,0) as roundoff, a.amount-a.discount+a.vat-isnull(sum(d.discount),0)-isnull(a.roundoff,0) as Net, ipd, a.reg, ");
            s.Append(" isnull( (select 'Y' from opd_morbidity with (nolock) where a.inv_no=inv_no group by inv_no ),' ' ) as IcdCode, e.referer, a.appby, a.reqby, ");
            s.Append(" a.telno, f.referer as consultant, g.taxable, g.nontaxable, a.patient_type, a.branch_center ");
            s.Append(" into #tOpdbill1 ");
            s.Append(" from opdbill a with (nolock) left join member b with (nolock) on a.hospid=b.hospid left join calendar c with (nolock) on a.ddate=c.ad_date ");
            s.Append(" left join (select inv_no, sum(discount) as discount from invoicediscount group by inv_no ) d on a.inv_no=d.inv_no left join referer e ");
            s.Append(" with (nolock) on a.refid=e.refid ");
            s.Append(" left join referer f with (nolock) on a.consid=f.refid ");
            s.Append(" left join (select * From #tOpdrec1 ) g on a.inv_no=g.inv_no ");
            s.Append(" left join userlist h on a.[user]=h.userid ");
            s.Append(" where ");
            s.Append(" a.ddate>=@init and a.ddate<=@final ");
            s.Append(" and (a.ddate + (a.billtime)>=case when @initbilltime='0' then a.ddate+a.billtime else @init + @initbilltime end ");
            s.Append(" and a.ddate+(a.billtime)<=case when @finalbilltime='0' then a.ddate + a.billtime else @final + @finalbilltime end) ");
            s.Append(" and a.firm= case when @firm=0 then a.firm else @firm end ");
            s.Append(" and a.ipd = case when @ipd = 2 then a.ipd else @ipd end ");
            s.Append(" and ( b.pname like '%'+@search+'%' or a.hospid like '%'+@search+'%' ) ");
            s.Append(" and ISNULL(case when @val=1 then a.refid when @val=0 then a.consid end,0) =case when @refid=0 ");
            s.Append(" then ISNULL(case when @val=1 then a.refid when @val=0 then a.consid end,0) else @refid end ");
            s.Append(" and a.er = case when @er=0 then a.er else @er end ");

            s.Append(" and a.discount=case when @discount=1 and a.DISCOUNT<>0 then a.discount ");
            s.Append("  when @discount=0 then a.discount end ");
   
            s.Append(" and a.AMOUNT= case when @salesbill=1 and a.amount>0 then a.amount ");
            s.Append("   when @salesbill= 0 then a.AMOUNT end  ");

            s.Append(" and a.AMOUNT= case when @returnbill=1 and a.amount<0 then a.amount ");
            s.Append("  when @returnbill= 0 then a.AMOUNT end ");

            s.Append(" and isnull(a.[canceled],0) = case when @canceled=0 then isnull(a.[canceled],0) else @canceled end ");
            s.Append(" and a.insurance = case when @insurance = 0 then a.insurance else @insurance end ");
            s.Append(" and a.[user] = case when 0=0 then a.[user] else 0 end ");
            s.Append(" and a.p_type=case when @paymode=0 then a.p_type ");
            s.Append(" when @paymode=1 and a.p_type='cash' then a.p_type ");
            s.Append(" when @paymode=2 and a.p_type='credit' then a.p_type ");
            s.Append(" when @paymode=3 and a.p_type='card' then a.p_type end ");
            s.Append(" and a.billmode=case when @billmode=0 then a.billmode ");
            s.Append(" when @billmode=1 and a.billmode='general' then a.billmode ");
            s.Append(" when @billmode=2 and a.billmode='member' then a.billmode end ");
            s.Append(" group by (case when @val=1 then a.refid ");
            s.Append(" when @val=0 then a.consid end) , ");
            s.Append(" a.insurance, a.canceled, a.note, a.hospid, c.bs_Date, a.ddate, a.inv_no, b.pname, b.address, b.telephone, a.amount, a.discount, ");
            s.Append(" a.vat, a.roundoff , ipd, a.reg, e.referer, a.appby, a.reqby, a.telno, f.referer, g.taxable, g.nontaxable, b.sex, cast( a.ageday/365 as int) , ");
            s.Append(" H.USERNAME ,a.note1, a.note2, A.PATIENT_TYPE, a.branch_center ");
            s.Append(" order by a.ddate, a.inv_no ");
            s.Append(" delete from topdbillReport where reportuserid=@userid ");
            s.Append(" insert into topdbillReport (note1 ,note2 ,refid , username, insurance, canceled, note , hospid , bs_date , ddate , inv_no , pname , [address] , ");
            s.Append(" telephone ,sex , age, amount , discount , vat , roundoff , net , ipd , reg , icdcode , referer , appby , reqby , telno , consultant , ");
            s.Append(" taxable , nontaxable , patient_type, branch_center , reportuserid ) ");
            s.Append(" select note1 ,note2 ,refid , username, insurance, canceled, note , hospid , bs_date , ddate , inv_no , pname , [address] , ");
            s.Append(" telephone ,sex , age, amount , discount , vat , roundoff , net , ipd , reg , icdcode , referer , appby , reqby , telno , consultant , ");
            s.Append(" taxable , nontaxable , patient_type, branch_center , @userid from #tOpdbill1 ");
            s.Append(" select *, case when discount>0 then (discount/amount)* 100 else 0 end as disc_pc from topdbillReport ");
            s.Append(" where ");
            s.Append(" (pname like '%'+@search+'%' or inv_no like '%%' or hospid like '%'+@search+'%' ) ");
            s.Append(" end ");
            s.Append(" end ");
            s.Append(" else ");
            s.Append(" begin ");
            s.Append(" select (case when @val=1 then a.refid ");
            s.Append(" when @val=0 then a.consid end) as refid , ");
            s.Append(" a.note1, a.note2, h.username, a.insurance, a.canceled, a.note, a.hospid, c.bs_Date, a.ddate, a.inv_no, b.pname,b.telephone, ");
            s.Append(" b.sex, cast( a.ageday/365 as int) as age, a.amount, a.discount, ");
            s.Append(" -isnull(a.roundoff,0) as roundoff, a.vat, a.amount-a.discount+a.vat as Net, ");
            s.Append(" ipd, cast( 0 as bit) as reg, cast( ' ' as varchar(1) ) as ICDCode, ' ' as referer, ' ' as appby, ' ' as reqby, ' ' as telno, ' ' as consultant, ");
            s.Append(" 0.00 as taxable, 0.00 as nontaxable, b.address , a.patient_type, a.branch_center ");
            s.Append(" into #tOpdbill2 ");
            s.Append(" from ipdbill_save a with (nolock) left join member b with (nolock) on a.hospid=b.hospid left join calendar c with (nolock) ");
            s.Append(" on a.ddate=c.ad_date LEFT JOIN USERLIST H ON A.[USER]=H.USERID ");
            s.Append(" where ");
            s.Append(" a.ddate>=@init and a.ddate<=@final ");
            s.Append(" and a.firm= case when @firm=0 then a.firm else @firm end ");
            s.Append(" and ( b.pname like '%'+@search+'%' or a.hospid like '%'+@search+'%' ) ");
            s.Append(" and a.[user] = case when 0=0 then a.[user] else 0 end ");
            s.Append(" order by a.ddate, a.inv_no ");
            s.Append(" delete from topdbillReport where reportuserid=@userid ");
            s.Append(" insert into topdbillReport (note1 ,note2 ,refid , username, insurance, canceled, note , hospid , bs_date , ddate , inv_no , pname , [address] , ");
            s.Append(" telephone ,sex , age, amount , discount , vat , roundoff , net , ipd , reg , icdcode , referer , appby , reqby , telno , consultant , ");
            s.Append(" taxable , nontaxable , patient_type, branch_center , reportuserid ) ");
            s.Append(" select note1 ,note2 ,refid , username, insurance, canceled, note , hospid , bs_date , ddate , inv_no , pname , [address] , ");
            s.Append(" telephone ,sex , age, amount , discount , vat , roundoff , net , ipd , reg , icdcode , referer , appby , reqby , telno , consultant , ");
            s.Append(" taxable , nontaxable , patient_type, branch_center , @userid from #tOpdbill2 ");
            s.Append(" select *, case when discount>0 then (discount/amount)* 100 else 0 end as disc_pc from topdbillReport ");
            s.Append(" where ");
            s.Append(" (pname like '%'+@search+'%' or inv_no like '%%' or hospid like '%'+@search+'%' ) ");
            s.Append(" end ");
            s.Append(" commit transaction ");
            s.Append(" end try ");
            s.Append(" begin catch ");
            s.Append(" declare @err_msg varchar(max), @errnunber varchar(max), @errstate varchar(max) ");
            s.Append(" select @err_msg= ERROR_MESSAGE() ,@errnunber = ERROR_NUMBER() , @errstate = ERROR_STATE() ");
            s.Append(" raiserror(@err_msg,16,1) ");
            s.Append(" rollback transaction ");
            s.Append(" end catch ");
            s.Append(" end ");




            try
            {
                DapperHelper.ExecuteSqlStatement(s.ToString());
            }
            catch (Exception ex)
            {
                Console.Write("Error info:" + ex.Message);

            }
        }



        public void SalesRegInvwise()
        {
            StringBuilder s = new StringBuilder();

            s.Append(" create procedure sp_SalesRegistrationbyInvoice ");
            s.Append(" (@init datetime,@final datetime,@firm int,@ipdsave int,@ipd int,@val int,@refid int, ");
            s.Append(" @er int, @discount int,@canceled int,@insurance int,@salesbill int,@returnbill int,@paymode int,@billmode int, ");
            s.Append(" @morbidity int,@search varchar(50) , @userid int,@start varchar(11),@end varchar(11)) ");
            s.Append(" as ");
            s.Append(" begin ");
            s.Append(" begin try ");
            s.Append(" begin transaction ");
            s.Append(" IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES ");
            s.Append(" WHERE TABLE_NAME = 'topdrecReport') ");
            s.Append(" DROP TABLE topdrecReport ");
            s.Append(" IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES ");
            s.Append(" WHERE TABLE_NAME = 'topdbillReport') ");
            s.Append(" DROP TABLE topdbillReport ");
            s.Append(" create table topdrecReport( ");
            s.Append(" inv_no varchar(11), amt float, disc_amt numeric(12,2), ");
            s.Append(" taxable numeric(12,2), nontaxable numeric(12,2), ");
            s.Append(" net numeric(12,2), reportuserid int ");
            s.Append(" ) ");
            s.Append(" create table topdbillReport( ");
            s.Append(" note1 varchar(30),note2 varchar(30),refid int , username varchar(50), insurance bit, canceled bit, note varchar(10), hospid int, ");
            s.Append(" bs_date varchar(10), ddate datetime, inv_no varchar(11), pname varchar(50), [address] varchar(250), ");
            s.Append(" telephone varchar(50),sex varchar(10), age int, amount float, discount float, vat float, roundoff numeric(12,2), net float, ipd bit, reg bit, ");
            s.Append(" icdcode varchar(1), referer varchar(50), appby varchar(30), reqby varchar(30), telno varchar(30), ");
            s.Append(" consultant varchar(50), taxable float, nontaxable float, patient_type varchar(20), branch_center varchar(20), reportuserid int ");
            s.Append(" ) ");
            s.Append(" if @ipdsave=0 ");
            s.Append(" begin ");
            s.Append(" if @morbidity=1 ");
            s.Append(" begin ");
            s.Append(" select inv_no, sum(qty*rate) as amt, sum(disc_amt) as disc_amt, ");
            s.Append(" sum(case when vatamt<>0 then (qty*rate)-disc_amt else 0 end) as taxable, ");
            s.Append(" sum(case when vatamt<>0 then 0 else (qty*rate)-disc_amt end) as nontaxable, ");
            s.Append(" sum(vatamt) as vatamt, sum( (qty*rate)-disc_amt+vatamt ) as net ");
            s.Append(" into #tOpdrecrep ");
            s.Append(" From opdrec where ddate>=@init and ddate<=@final and firm= case when @firm=0 then firm else @firm end ");
            s.Append(" group by inv_no ");
            s.Append(" delete from topdrecReport where reportuserid=@userid ");
            s.Append(" insert into topdrecReport(inv_no , amt , disc_amt ,taxable , nontaxable ,net , reportuserid) ");
            s.Append(" select inv_no , amt , disc_amt ,taxable , nontaxable ,net , @userid from #topdrecrep ");
            s.Append(" select a.note1, a.note2, (case when @val=1 then a.refid ");
            s.Append(" when @val=0 then a.consid end) as refid, h.username, a.insurance, a.canceled, a.note, a.hospid, c.bs_Date, a.ddate, a.inv_no, ");
            s.Append(" b.pname, b.address, b.telephone, b.sex, cast( a.ageday/365 as int) as age, a.amount, a.discount+isnull(sum(d.discount),0) as discount , ");
            s.Append(" a.vat, -isnull(a.roundoff,0) as roundoff, a.amount-a.discount+a.vat-isnull(sum(d.discount),0)-isnull(a.roundoff,0) as Net, ipd, a.reg, ");
            s.Append(" isnull( (select 'Y' from opd_morbidity with (nolock) where a.inv_no=inv_no group by inv_no ),' ' ) as IcdCode, e.referer, a.appby, a.reqby, a.telno, f.referer as consultant, ");
            s.Append(" g.taxable, g.nontaxable, a.patient_type, a.branch_center ");
            s.Append(" into #tOpdbill ");
            s.Append(" from opdbill a with (nolock) left join member b with (nolock) on a.hospid=b.hospid left join calendar c with (nolock) on a.ddate=c.ad_date ");
            s.Append(" left join (select inv_no, sum(discount) as discount from invoicediscount group by inv_no ) d on a.inv_no=d.inv_no left join referer e with (nolock) on a.refid=e.refid ");
            s.Append(" left join referer f with (nolock) on a.consid=f.refid ");
            s.Append(" left join (select * From #topdrecrep ) g on a.inv_no=g.inv_no ");
            s.Append(" left join userlist h on a.[user]=h.userid ");
            s.Append(" where ");
            s.Append(" a.inv_no>=@start and a.inv_no<=@end ");
            s.Append(" and a.firm= case when @firm=0 then a.firm else @firm end  ");
            s.Append(" and a.ipd = case when @ipd = 2 then a.ipd else @ipd end ");
            s.Append(" and ( b.pname like '%'+@search+'%' or a.hospid like '%'+@search+'%') ");
            s.Append(" and ISNULL(case when @val=1 then a.refid when @val=0 then a.consid end,0) =case when @refid=0 ");
            s.Append(" then ISNULL(case when @val=1 then a.refid when @val=0 then a.consid end,0) else @refid end ");
            s.Append(" and a.er = case when @er=0 then a.er else @er end ");
            s.Append(" and a.discount=case when @discount=1 and a.DISCOUNT<>0 then a.discount ");
            s.Append(" when @discount=0 then a.discount end ");
            s.Append(" and a.AMOUNT= case when @salesbill=1 and a.amount>0 then a.amount ");
            s.Append(" when @salesbill= 0 then a.AMOUNT end ");
            s.Append(" and a.AMOUNT= case when @returnbill=1 and a.amount<0 then a.amount ");
            s.Append(" when @returnbill= 0 then a.AMOUNT end ");
            s.Append(" and isnull(a.[canceled],0) = case when @canceled=0 then isnull(a.[canceled],0) else @canceled end ");
            s.Append(" and a.insurance = case when @insurance = 0 then a.insurance else @insurance end ");
            s.Append(" and a.[user] = case when 0=0 then a.[user] else 0 end ");
            s.Append(" and a.p_type=case when @paymode=0 then a.p_type ");
            s.Append(" when @paymode=1 and a.p_type='cash' then a.p_type ");
            s.Append(" when @paymode=2 and a.p_type='credit' then a.p_type ");
            s.Append(" when @paymode=3 and a.p_type='card' then a.p_type end ");
            s.Append(" and a.billmode=case when @billmode=0 then a.billmode ");
            s.Append(" when @billmode=1 and a.billmode='general' then a.billmode ");
            s.Append(" when @billmode=2 and a.billmode='member' then a.billmode end ");
            s.Append(" and a.inv_no in (select e.inv_no from opdrec e with (nolock) left join service f with (nolock) on e.servid=f.servid ");
            s.Append(" where e.inv_no>=@start and e.inv_no<=@end and f.grpid=124 ) ");
            s.Append(" group by (case when @val=1 then a.refid ");
            s.Append(" when @val=0 then a.consid end) , a.insurance, a.canceled, a.note, a.hospid, c.bs_Date, a.ddate, a.inv_no, b.pname, b.address, b.telephone, a.amount, a.discount, ");
            s.Append(" a.vat, a.roundoff , ipd, a.reg, e.referer, a.appby, a.reqby, a.telno, f.referer, g.taxable, g.nontaxable, b.sex, cast( a.ageday/365 as int) , H.USERNAME , ");
            s.Append(" a.note1, a.note2, A.PATIENT_TYPE, a.branch_center ");
            s.Append(" order by a.ddate, a.inv_no ");
            s.Append(" delete from topdbillReport where reportuserid=@userid ");
            s.Append(" insert into topdbillReport (note1 ,note2 ,refid , username, insurance, canceled, note , hospid , bs_date , ddate , inv_no , pname , [address] , ");
            s.Append(" telephone ,sex , age, amount , discount , vat , roundoff , net , ipd , reg , icdcode , referer , appby , reqby , telno , consultant , ");
            s.Append(" taxable , nontaxable , patient_type, branch_center , reportuserid ) ");
            s.Append(" select note1 ,note2 ,refid , username, insurance, canceled, note , hospid , bs_date , ddate , inv_no , pname , [address] , ");
            s.Append(" telephone ,sex , age, amount , discount , vat , roundoff , net , ipd , reg , icdcode , referer , appby , reqby , telno , consultant , ");
            s.Append(" taxable , nontaxable , patient_type, branch_center , @userid from #tOpdbill ");
            s.Append(" select *, case when discount>0 then (discount/amount)* 100 else 0 end as disc_pc from topdbillReport ");
            s.Append(" where ");
            s.Append(" (pname like '%'+@search+'%' or inv_no like '%'+@search+'%' or hospid like '%'+@search+'%' ) ");
            s.Append(" end ");
            s.Append(" else ");
            s.Append(" begin ");
            s.Append(" select inv_no, sum(qty*rate) as amt, sum(disc_amt) as disc_amt, ");
            s.Append(" sum(case when vatamt<>0 then (qty*rate)-disc_amt else 0 end) as taxable, ");
            s.Append(" sum(case when vatamt<>0 then 0 else (qty*rate)-disc_amt end) as nontaxable, ");
            s.Append(" sum(vatamt) as vatamt, sum( (qty*rate)-disc_amt+vatamt ) as net ");
            s.Append(" into #topdrec1 ");
            s.Append(" From opdrec where ddate>=@init and ddate<=@final and firm= case when @firm=0 then firm else @firm end ");
            s.Append(" group by inv_no ");
            s.Append(" delete from topdrecReport where reportuserid=@userid ");
            s.Append(" insert into topdrecReport(inv_no , amt , disc_amt ,taxable , nontaxable ,net , reportuserid) ");
            s.Append(" select inv_no , amt , disc_amt ,taxable , nontaxable ,net , @userid from #topdrec1 ");
            s.Append(" select a.note1, a.note2,(case when @val=1 then a.refid ");
            s.Append(" when @val=0 then a.consid end) as refid, h.username, a.insurance, a.canceled, a.note, a.hospid, c.bs_Date, a.ddate, a.inv_no, ");
            s.Append(" b.pname, b.address, b.telephone, b.sex, cast( a.ageday/365 as int) as age, a.amount, a.discount+isnull(sum(d.discount),0) as discount , ");
            s.Append(" a.vat, -isnull(a.roundoff,0) as roundoff, a.amount-a.discount+a.vat-isnull(sum(d.discount),0)-isnull(a.roundoff,0) as Net, ipd, a.reg, ");
            s.Append(" isnull( (select 'Y' from opd_morbidity with (nolock) where a.inv_no=inv_no group by inv_no ),' ' ) as IcdCode, e.referer, a.appby, a.reqby, ");
            s.Append(" a.telno, f.referer as consultant, g.taxable, g.nontaxable, a.patient_type, a.branch_center ");
            s.Append(" into #tOpdbill1 ");
            s.Append(" from opdbill a with (nolock) left join member b with (nolock) on a.hospid=b.hospid left join calendar c with (nolock) on a.ddate=c.ad_date ");
            s.Append(" left join (select inv_no, sum(discount) as discount from invoicediscount group by inv_no ) d on a.inv_no=d.inv_no left join referer e ");
            s.Append(" with (nolock) on a.refid=e.refid ");
            s.Append(" left join referer f with (nolock) on a.consid=f.refid ");
            s.Append(" left join (select * From #tOpdrec1 ) g on a.inv_no=g.inv_no ");
            s.Append(" left join userlist h on a.[user]=h.userid ");
            s.Append(" where ");
            s.Append(" a.inv_no>=@start and a.inv_no<=@end ");
            s.Append(" and a.firm= case when @firm=0 then a.firm else @firm end ");
            s.Append(" and a.ipd = case when @ipd = 2 then a.ipd else @ipd end ");
            s.Append(" and ( b.pname like '%'+@search+'%' or a.hospid like '%'+@search+'%' ) ");
            s.Append(" and ISNULL(case when @val=1 then a.refid when @val=0 then a.consid end,0) =case when @refid=0 ");
            s.Append(" then ISNULL(case when @val=1 then a.refid when @val=0 then a.consid end,0) else @refid end ");
            s.Append(" and a.er = case when @er=0 then a.er else @er end ");
            s.Append(" and a.discount=case when @discount=1 and a.DISCOUNT<>0 then a.discount ");
            s.Append(" when @discount=0 then a.discount end ");
            s.Append(" and a.AMOUNT= case when @salesbill=1 and a.amount>0 then a.amount ");
            s.Append(" when @salesbill= 0 then a.AMOUNT end ");
            s.Append(" and a.AMOUNT= case when @returnbill=1 and a.amount<0 then a.amount ");
            s.Append(" when @returnbill= 0 then a.AMOUNT end ");
            s.Append(" and isnull(a.[canceled],0) = case when @canceled=0 then isnull(a.[canceled],0) else @canceled end ");
            s.Append(" and a.insurance = case when @insurance = 0 then a.insurance else @insurance end ");
            s.Append(" and a.[user] = case when 0=0 then a.[user] else 0 end ");
            s.Append(" and a.p_type=case when @paymode=0 then a.p_type ");
            s.Append(" when @paymode=1 and a.p_type='cash' then a.p_type ");
            s.Append(" when @paymode=2 and a.p_type='credit' then a.p_type ");
            s.Append(" when @paymode=3 and a.p_type='card' then a.p_type end ");
            s.Append(" and a.billmode=case when @billmode=0 then a.billmode ");
            s.Append(" when @billmode=1 and a.billmode='general' then a.billmode ");
            s.Append(" when @billmode=2 and a.billmode='member' then a.billmode end ");
            s.Append(" group by (case when @val=1 then a.refid ");
            s.Append(" when @val=0 then a.consid end) , a.insurance, a.canceled, a.note, a.hospid, c.bs_Date, a.ddate, a.inv_no, b.pname, b.address, b.telephone, a.amount, a.discount, ");
            s.Append(" a.vat, a.roundoff , ipd, a.reg, e.referer, a.appby, a.reqby, a.telno, f.referer, g.taxable, g.nontaxable, b.sex, cast( a.ageday/365 as int) , ");
            s.Append(" H.USERNAME ,a.note1, a.note2, A.PATIENT_TYPE, a.branch_center ");
            s.Append(" order by a.ddate, a.inv_no ");
            s.Append(" delete from topdbillReport where reportuserid=@userid ");
            s.Append(" insert into topdbillReport (note1 ,note2 ,refid , username, insurance, canceled, note , hospid , bs_date , ddate , inv_no , pname , [address] , ");
            s.Append(" telephone ,sex , age, amount , discount , vat , roundoff , net , ipd , reg , icdcode , referer , appby , reqby , telno , consultant , ");
            s.Append(" taxable , nontaxable , patient_type, branch_center , reportuserid ) ");
            s.Append(" select note1 ,note2 ,refid , username, insurance, canceled, note , hospid , bs_date , ddate , inv_no , pname , [address] , ");
            s.Append(" telephone ,sex , age, amount , discount , vat , roundoff , net , ipd , reg , icdcode , referer , appby , reqby , telno , consultant , ");
            s.Append(" taxable , nontaxable , patient_type, branch_center , @userid from #tOpdbill1 ");
            s.Append(" select *, case when discount>0 then (discount/amount)* 100 else 0 end as disc_pc from topdbillReport ");
            s.Append(" where ");
            s.Append(" (pname like '%'+@search+'%' or inv_no like '%'+@search+'%' or hospid like '%'+@search+'%' ) ");
            s.Append(" end ");
            s.Append(" end ");
            s.Append(" else ");
            s.Append(" begin ");
            s.Append(" select (case when @val=1 then a.refid ");
            s.Append(" when @val=0 then a.consid end) as refid, a.note1, a.note2, h.username, a.insurance, a.canceled, a.note, a.hospid, c.bs_Date, a.ddate, a.inv_no, b.pname,b.telephone, ");
            s.Append(" b.sex, cast( a.ageday/365 as int) as age, a.amount, a.discount, ");
            s.Append(" -isnull(a.roundoff,0) as roundoff, a.vat, a.amount-a.discount+a.vat as Net, ");
            s.Append(" ipd, cast( 0 as bit) as reg, cast( ' ' as varchar(1) ) as ICDCode, ' ' as referer, ' ' as appby, ' ' as reqby, ' ' as telno, ' ' as consultant, ");
            s.Append(" 0.00 as taxable, 0.00 as nontaxable, b.address , a.patient_type, a.branch_center ");
            s.Append(" into #tOpdbill2 ");
            s.Append(" from ipdbill_save a with (nolock) left join member b with (nolock) on a.hospid=b.hospid left join calendar c with (nolock) ");
            s.Append(" on a.ddate=c.ad_date LEFT JOIN USERLIST H ON A.[USER]=H.USERID ");
            s.Append(" where ");
            s.Append(" a.inv_no>=@start and a.inv_no<=@end ");
            s.Append(" and a.firm= case when @firm=0 then a.firm else @firm end ");
            s.Append(" and ( b.pname like '%'+@search+'%' or a.hospid like '%'+@search+'%' ) ");
            s.Append(" and a.[user] = case when 0=0 then a.[user] else 0 end ");
            s.Append(" order by a.ddate, a.inv_no ");
            s.Append(" delete from topdbillReport where reportuserid=@userid ");
            s.Append(" insert into topdbillReport (note1 ,note2 ,refid , username, insurance, canceled, note , hospid , bs_date , ddate , inv_no , pname , [address] , ");
            s.Append(" telephone ,sex , age, amount , discount , vat , roundoff , net , ipd , reg , icdcode , referer , appby , reqby , telno , consultant , ");
            s.Append(" taxable , nontaxable , patient_type, branch_center , reportuserid ) ");
            s.Append(" select note1 ,note2 ,refid , username, insurance, canceled, note , hospid , bs_date , ddate , inv_no , pname , [address] , ");
            s.Append(" telephone ,sex , age, amount , discount , vat , roundoff , net , ipd , reg , icdcode , referer , appby , reqby , telno , consultant , ");
            s.Append(" taxable , nontaxable , patient_type, branch_center , @userid from #tOpdbill2 ");
            s.Append(" select *, case when discount>0 then (discount/amount)* 100 else 0 end as disc_pc from topdbillReport ");
            s.Append(" where ");
            s.Append(" (pname like '%'+@search+'%' or inv_no like '%'+@search+'%' or hospid like '%'+@search+'%' ) ");
            s.Append(" end ");
            s.Append(" commit transaction ");
            s.Append(" end try ");
            s.Append(" begin catch ");
            s.Append(" declare @err_msg varchar(max), @errnunber varchar(max), @errstate varchar(max) ");
            s.Append(" select @err_msg= ERROR_MESSAGE() ,@errnunber = ERROR_NUMBER() , @errstate = ERROR_STATE() ");
            s.Append(" raiserror(@err_msg,16,1) ");
            s.Append(" rollback transaction ");
            s.Append(" end catch ");
            s.Append(" end ");




            try
            {
                DapperHelper.ExecuteSqlStatement(s.ToString());
            }
            catch (Exception ex)
            {
                Console.Write("Error info:" + ex.Message);

            }
        }
    }
}